// Technical format identifiers remain unchanged; descriptions and controls are localized.
type ExtraToolCopy = {
  names: Record<string, string>;
  options: Record<string, string>;
  signature: { title: string; hint: string; clear: string; upload: string; uploadError: string };
  thumbnails: { title: string; loading: string; selection: string; reorder: string; page: string; selected: string; limited: (count: number) => string; failed: string };
  guides: Record<string, { title: string; intro: string; sections: Array<[string, string]> }>;
};
export const additionalToolCopy: Record<"ko" | "it", ExtraToolCopy> = {
  ko: {
    names: {
      "Merge PDF": "PDF 합치기", "Split PDF": "PDF 나누기", "Rotate PDF": "PDF 회전", "Reorder Pages": "페이지 순서 변경", "Extract Pages": "페이지 추출", "Delete Pages": "페이지 삭제", "Reverse PDF": "PDF 역순 정렬", "Duplicate Pages": "페이지 복제", "Compress PDF": "PDF 압축", "Add Watermark": "워터마크 추가", "Add Page Numbers": "페이지 번호 추가", "Edit Metadata": "메타데이터 편집", "Crop PDF": "PDF 자르기", "Flatten PDF": "PDF 평면화", "Header & Footer": "머리글 및 바닥글", "Resize PDF": "PDF 크기 조절", "Sign PDF": "PDF 서명", "Unlock PDF": "PDF 잠금 해제", "Protect PDF": "PDF 암호 설정", "Compare PDF": "PDF 비교", "Redact PDF": "PDF 민감 정보 삭제", "PDF OCR": "PDF 문자 인식", "Sanitize PDF": "PDF 정리", "Verify PDF": "PDF 검증", "SVG Color Editor": "SVG 색상 편집", "SVG Palette Swapper": "SVG 팔레트 변경", "SVG Optimizer": "SVG 최적화", "SVG Pattern Maker": "SVG 패턴 만들기", "SVG QR Code": "SVG QR 코드", "Image Compressor": "이미지 압축", "Resize Image": "이미지 크기 조절", "Crop Image": "이미지 자르기", "Rotate Image": "이미지 회전", "Image Background": "이미지 배경", "Remove EXIF": "EXIF 제거", "Icon Resource Pack": "아이콘 리소스 모음"
    },
    options: {
      "Page range": "페이지 범위", "Page order (for example 2,1,3)": "페이지 순서 (예: 2,1,3)", "Pages to duplicate": "복제할 페이지", Repeats: "반복 횟수", "Insert position": "삽입 위치", Quality: "품질", "Resolution (DPI)": "해상도 (DPI)", "Create one long image": "긴 이미지 하나로 만들기", Paper: "용지", Orientation: "방향", "Margin (pt)": "여백 (pt)", Fit: "맞춤 방식", "Background color": "배경색", "Frame (1 = first)": "프레임 (1 = 첫 프레임)", "Compression mode": "압축 방식", "Watermark text": "워터마크 텍스트", "Text size": "글자 크기", Position: "위치", Rotation: "회전", Opacity: "불투명도", "Start number": "시작 번호", "Page number format ({page} supported)": "페이지 번호 형식 ({page} 지원)", Title: "제목", Author: "작성자", Subject: "주제", Keywords: "키워드", "Crop inset (pt)": "안쪽 자르기 (pt)", "Header ({page} supported)": "머리글 ({page} 지원)", "Footer ({page} supported)": "바닥글 ({page} 지원)", "Page preset": "페이지 설정", "Page width (pt)": "페이지 너비 (pt)", "Page height (pt)": "페이지 높이 (pt)", "Signature text": "서명 텍스트", "PDF password": "PDF 비밀번호", "New PDF password": "새 PDF 비밀번호", "Visual page diff": "페이지 시각 비교", "Terms to remove (comma separated)": "삭제할 단어 (쉼표로 구분)", "OCR language(s)": "OCR 인식 언어", "Replacement color": "바꿀 색상", Palette: "팔레트", Width: "너비", Height: "높이", Scale: "배율", "QR content": "QR 내용", "Error correction": "오류 정정", Flip: "뒤집기", Padding: "내부 여백"
    },
    signature: { title: "서명 모양 그리기 또는 업로드", hint: "시각적인 서명만 생성하며 인증서 기반 전자서명이 아닙니다.", clear: "그림 지우기", upload: "이미지 사용", uploadError: "PNG, JPG, WebP 형식의 4 MB 미만 이미지를 사용하세요." },
    thumbnails: { title: "페이지 미리보기", loading: "페이지를 로컬에서 그리는 중…", selection: "처리할 페이지를 선택하세요.", reorder: "드래그, 앞/뒤 이동 버튼, 또는 초점을 맞춘 뒤 ← → 키로 정렬하세요.", page: "페이지", selected: "선택됨", limited: (count: number) => `처음 ${count}페이지만 표시합니다. 이후 페이지는 범위 입력을 사용하세요.`, failed: "미리보기를 그릴 수 없습니다. 페이지 범위 입력은 계속 사용할 수 있습니다." },
    guides: {
      "prepare-images-for-web": { title: "웹용 이미지 준비", intro: "웹에 사용할 이미지의 치수, 형식과 품질을 선택하는 실용적인 가이드입니다.", sections: [["용도에 맞는 형식", "투명 이미지에는 PNG, 사진에는 JPEG를 고려하세요. WebP와 AVIF는 대상 브라우저의 지원 여부를 확인하세요."], ["압축 전에 크기 조절", "표시 크기보다 큰 이미지는 먼저 축소하세요. 디코딩 픽셀을 줄이면 메모리 사용량도 줄일 수 있습니다."], ["결과 확인", "크기와 치수, 투명도를 확인하세요. 형식을 변환하면 파일이 더 커질 수도 있습니다."]] },
      "pdf-privacy-basics": { title: "PDF 개인정보 보호 기초", intro: "PDF를 공유하기 전에 확인할 사항과 로컬 도구가 보장할 수 없는 부분을 설명합니다.", sections: [["작업의 차이", "자르기는 보이는 영역만 바꿉니다. 민감 정보 삭제는 실제 내용을 제거해야 합니다. 평면화는 지원되는 양식과 주석 동작을 바꿉니다."], ["공유 전에 확인", "메타데이터와 숨겨진 정보를 확인하세요. 서명 검증은 구조, 암호화와 신뢰 상태를 구분하며 알 수 없는 신뢰를 유효하다고 표시하지 않습니다."], ["처리 방식 확인", "로컬 작업은 업로드하지 않습니다. 서버 작업은 동의를 요청하고 임시 결과를 사용합니다. 파일 삭제는 물리적 저장 매체 삭제를 보증하지 않습니다."]] }
    }
  },
  it: {
    names: {
      "Merge PDF": "Unisci PDF", "Split PDF": "Dividi PDF", "Rotate PDF": "Ruota PDF", "Reorder Pages": "Riordina pagine", "Extract Pages": "Estrai pagine", "Delete Pages": "Elimina pagine", "Reverse PDF": "Inverti PDF", "Duplicate Pages": "Duplica pagine", "Compress PDF": "Comprimi PDF", "Add Watermark": "Aggiungi filigrana", "Add Page Numbers": "Aggiungi numeri di pagina", "Edit Metadata": "Modifica metadati", "Crop PDF": "Ritaglia PDF", "Flatten PDF": "Appiattisci PDF", "Header & Footer": "Intestazione e piè di pagina", "Resize PDF": "Ridimensiona PDF", "Sign PDF": "Firma PDF", "Unlock PDF": "Sblocca PDF", "Protect PDF": "Proteggi PDF", "Compare PDF": "Confronta PDF", "Redact PDF": "Oscura dati nel PDF", "PDF OCR": "Riconoscimento testo PDF", "Sanitize PDF": "Pulisci PDF", "Verify PDF": "Verifica PDF", "SVG Color Editor": "Editor colori SVG", "SVG Palette Swapper": "Cambia palette SVG", "SVG Optimizer": "Ottimizza SVG", "SVG Pattern Maker": "Crea motivi SVG", "SVG QR Code": "Codice QR SVG", "Image Compressor": "Comprimi immagini", "Resize Image": "Ridimensiona immagine", "Crop Image": "Ritaglia immagine", "Rotate Image": "Ruota immagine", "Image Background": "Sfondo immagine", "Remove EXIF": "Rimuovi EXIF", "Icon Resource Pack": "Pacchetto risorse icona"
    },
    options: {
      "Page range": "Intervallo pagine", "Page order (for example 2,1,3)": "Ordine pagine (ad esempio 2,1,3)", "Pages to duplicate": "Pagine da duplicare", Repeats: "Ripetizioni", "Insert position": "Posizione di inserimento", Quality: "Qualità", "Resolution (DPI)": "Risoluzione (DPI)", "Create one long image": "Crea un'unica immagine lunga", Paper: "Carta", Orientation: "Orientamento", "Margin (pt)": "Margine (pt)", Fit: "Adattamento", "Background color": "Colore di sfondo", "Frame (1 = first)": "Fotogramma (1 = primo)", "Compression mode": "Modalità di compressione", "Watermark text": "Testo filigrana", "Text size": "Dimensione testo", Position: "Posizione", Rotation: "Rotazione", Opacity: "Opacità", "Start number": "Numero iniziale", "Page number format ({page} supported)": "Formato numero pagina (supporta {page})", Title: "Titolo", Author: "Autore", Subject: "Oggetto", Keywords: "Parole chiave", "Crop inset (pt)": "Ritaglio interno (pt)", "Header ({page} supported)": "Intestazione (supporta {page})", "Footer ({page} supported)": "Piè di pagina (supporta {page})", "Page preset": "Formato pagina predefinito", "Page width (pt)": "Larghezza pagina (pt)", "Page height (pt)": "Altezza pagina (pt)", "Signature text": "Testo firma", "PDF password": "Password PDF", "New PDF password": "Nuova password PDF", "Visual page diff": "Confronto visivo delle pagine", "Terms to remove (comma separated)": "Termini da rimuovere (separati da virgole)", "OCR language(s)": "Lingue di riconoscimento OCR", "Replacement color": "Colore sostitutivo", Palette: "Palette", Width: "Larghezza", Height: "Altezza", Scale: "Scala", "QR content": "Contenuto QR", "Error correction": "Correzione errori", Flip: "Rifletti", Padding: "Margine interno"
    },
    signature: { title: "Disegna o carica una firma grafica", hint: "Il risultato è solo visivo, non una firma digitale basata su certificato.", clear: "Cancella disegno", upload: "Usa un'immagine", uploadError: "Usa un'immagine PNG, JPG o WebP inferiore a 4 MB." },
    thumbnails: { title: "Miniature delle pagine", loading: "Rendering locale delle pagine…", selection: "Scegli le pagine da elaborare.", reorder: "Trascina per riordinare, usa i pulsanti di spostamento oppure ← → quando la pagina ha il focus.", page: "Pagina", selected: "Selezionata", limited: (count: number) => `Sono mostrate le prime ${count} pagine. Usa il campo intervallo per le successive.`, failed: "Impossibile creare le miniature. Il campo intervallo pagine è ancora disponibile." },
    guides: {
      "prepare-images-for-web": { title: "Preparare immagini per il web", intro: "Una guida pratica per scegliere dimensioni, formato e qualità delle immagini da pubblicare sul web.", sections: [["Scegli in base alla destinazione", "Considera PNG per la trasparenza e JPEG per le fotografie. Verifica il supporto del browser prima di scegliere WebP o AVIF."], ["Ridimensiona prima di comprimere", "Riduci prima le immagini più grandi della dimensione di visualizzazione. Meno pixel decodificati significano anche meno memoria occupata."], ["Controlla il risultato", "Verifica dimensioni, risoluzione e trasparenza. Una conversione può produrre un file più grande."]] },
      "pdf-privacy-basics": { title: "Nozioni di privacy dei PDF", intro: "Cosa controllare prima di condividere un PDF e quali garanzie un elaboratore locale non può offrire.", sections: [["Distingui le operazioni", "Il ritaglio cambia solo l'area visibile. L'oscuramento deve rimuovere i contenuti sottostanti. L'appiattimento modifica moduli e annotazioni supportati."], ["Controlla prima di condividere", "Verifica metadati e informazioni nascoste. La verifica distingue struttura, cifratura e fiducia nelle firme: una fiducia sconosciuta non diventa valida."], ["Verifica la modalità di elaborazione", "Le attività locali non caricano file. Il server richiede consenso e usa risultati temporanei. Eliminare un file non garantisce la cancellazione fisica del supporto."]] }
    }
  }
};

export function additionalToolName(locale: "ko" | "it", name: string) {
  const names: Record<string, string> = additionalToolCopy[locale].names;
  if (names[name]) return names[name];
  if (name.startsWith("Compress ")) return locale === "ko" ? `${name.slice(9)} 압축` : `Comprimi ${name.slice(9)}`;
  const [from, to] = name.split(" to ");
  if (to) return locale === "ko" ? `${from} → ${to === "Text" ? "텍스트" : to === "Favicon" ? "파비콘" : to}` : `Da ${from} a ${to === "Text" ? "testo" : to}`;
  throw new Error(`Missing ${locale} tool name: ${name}`);
}
