import { getWorkspaceCopy } from "./workspace-copy";
import { pixelLimitText } from "./pixel-limits";
import { expandedMap, packMap, expandedToolName, isExpandedLocale } from "./expanded-locales";
import { formatLocale } from "./expanded-locale-schema";
import { additionalLocales } from "./additional-locales";
import { additionalToolCopy, additionalToolName } from "./additional-tool-copy";
import type { Locale, Tool, ToolCategory } from "@hxsl/tool-registry";
import { LOCALES } from "@hxsl/tool-registry";

export const localeNames: Record<Locale, string> = {
  ...packMap(c => c.name),
  ko: additionalLocales.ko.name, it: additionalLocales.it.name,

  en: "English", "zh-CN": "简体中文", "zh-TW": "繁體中文", es: "Español", "pt-BR": "Português (Brasil)", de: "Deutsch", fr: "Français", ja: "日本語",
};

type Messages = {
  nav: { tools: string; guides: string; privacy: string; about: string };
  home: { eyebrow: string; title: string; description: string; primary: string; secondary: string; featured: string; featuredDescription: string; workflow: string; workflowDescription: string; privacyTitle: string; privacyDescription: string; browse: string };
  workspace: { dropTitle: string; dropDescription: string; choose: string; process: string; clear: string; remove: string; waiting: string; working: string; ready: string; failed: string; local: string; server: string; hybrid: string; format: string; size: string; output: string; consent: string; serverConsent: string; download: string; noFiles: string };
  category: Record<ToolCategory, string>;
  common: { steps: string; limits: string; privacy: string; related: string; faq: string; input: string; output: string; honest: string; notFound: string };
};

const en: Messages = {
  nav: { tools: "Tools", guides: "Guides", privacy: "Privacy", about: "About" },
  home: { eyebrow: "Local-first file work", title: "Make files easier to use.", description: "Practical PDF, image, SVG and icon tools that keep your files close and your outputs honest.", primary: "Browse tools", secondary: "How privacy works", featured: "Start with a real task", featuredDescription: "Four focused workbenches for the work people actually need to finish.", workflow: "A calmer file workflow", workflowDescription: "Choose a task, add a file, check the result. No account, no mystery queue.", privacyTitle: "Your files stay yours by default.", privacyDescription: "Browser tools process locally. Server tools say when upload is needed, ask first, and clean results after 15 minutes.", browse: "View all" },
  workspace: { dropTitle: "Drop files here", dropDescription: "or choose files from this device. Processing starts only when you press the button.", choose: "Choose files", process: "Process files", clear: "Clear all", remove: "Remove", waiting: "Waiting", working: "Working", ready: "Ready to download", failed: "Could not process", local: "Local", server: "Server", hybrid: "Upload only with consent", format: "Format", size: "Size", output: "Output", consent: "I understand this file will be uploaded for this task.", serverConsent: "Server processing requires your explicit consent.", download: "Download", noFiles: "Add at least one file to begin." },
  category: { pdf: "PDF Tools", image: "Image Tools", svg: "SVG Tools", icons: "Icon Tools" },
  common: { steps: "How it works", limits: "Limits and support", privacy: "Privacy note", related: "Continue with", faq: "Common questions", input: "Input", output: "Output", honest: "Output is checked after processing. If there is no size saving, the original is kept for compression tasks.", notFound: "That page does not exist." },
};

const translations: Partial<Record<Locale, Partial<Messages>>> = {
  ...packMap(c => c.messages),
  ko: additionalLocales.ko.messages, it: additionalLocales.it.messages,

  "zh-CN": { nav: { tools: "工具", guides: "指南", privacy: "隐私", about: "关于" }, home: { eyebrow: "本地优先的文件处理", title: "让文件更好用。", description: "实用的 PDF、图片、SVG 和图标工具，让文件留在设备上，结果清晰可验证。", primary: "浏览工具", secondary: "了解隐私", featured: "从真实任务开始", featuredDescription: "四个专注的工作台，覆盖日常文件处理。", workflow: "更从容的文件流程", workflowDescription: "选择任务，添加文件，检查结果。不需要账号，也没有不透明队列。", privacyTitle: "默认让文件留在你手里。", privacyDescription: "浏览器工具在本地处理。需要上传的服务端工具会先说明、先征得同意，并在 15 分钟后清理结果。", browse: "查看全部" }, workspace: { dropTitle: "将文件拖到这里", dropDescription: "也可以从设备选择文件。只有按下处理按钮后才会开始。", choose: "选择文件", process: "处理文件", clear: "全部清除", remove: "移除", waiting: "等待中", working: "处理中", ready: "可以下载", failed: "处理失败", local: "本地", server: "服务端", hybrid: "同意后上传", format: "格式", size: "大小", output: "输出", consent: "我了解此任务会上传文件。", serverConsent: "服务端处理需要你的明确同意。", download: "下载", noFiles: "请先添加至少一个文件。" }, category: { pdf: "PDF 工具", image: "图片工具", svg: "SVG 工具", icons: "图标工具" }, common: { steps: "使用步骤", limits: "限制与支持", privacy: "隐私说明", related: "继续使用", faq: "常见问题", input: "输入", output: "输出", honest: "处理后会检查输出。如果压缩没有节省空间，会保留原文件。", notFound: "页面不存在。" } },
  "zh-TW": { nav: { tools: "工具", guides: "指南", privacy: "隱私", about: "關於" }, home: { eyebrow: "本機優先的檔案處理", title: "讓檔案更好用。", description: "實用的 PDF、圖片、SVG 與圖示工具，讓檔案留在裝置上，結果清楚可驗證。", primary: "瀏覽工具", secondary: "了解隱私", featured: "從真實任務開始", featuredDescription: "四個專注工作台，處理日常檔案工作。", workflow: "更從容的檔案流程", workflowDescription: "選擇任務、加入檔案、檢查結果。不需帳號，也沒有不透明的佇列。", privacyTitle: "檔案預設留在你手中。", privacyDescription: "瀏覽器工具在本機處理。需要上傳的伺服器工具會先說明、先徵得同意，並在 15 分鐘後清理結果。", browse: "查看全部" }, workspace: { dropTitle: "將檔案拖曳到這裡", dropDescription: "也可以從裝置選擇檔案。按下處理按鈕後才會開始。", choose: "選擇檔案", process: "處理檔案", clear: "全部清除", remove: "移除", waiting: "等待中", working: "處理中", ready: "可以下載", failed: "處理失敗", local: "本機", server: "伺服器", hybrid: "同意後上傳", format: "格式", size: "大小", output: "輸出", consent: "我了解此任務會上傳檔案。", serverConsent: "伺服器處理需要你的明確同意。", download: "下載", noFiles: "請先加入至少一個檔案。" }, category: { pdf: "PDF 工具", image: "圖片工具", svg: "SVG 工具", icons: "圖示工具" }, common: { steps: "使用步驟", limits: "限制與支援", privacy: "隱私說明", related: "繼續使用", faq: "常見問題", input: "輸入", output: "輸出", honest: "處理後會檢查輸出。若壓縮沒有節省空間，會保留原檔案。", notFound: "頁面不存在。" } },
  es: { nav: { tools: "Herramientas", guides: "Guías", privacy: "Privacidad", about: "Acerca de" }, home: { eyebrow: "Procesamiento local", title: "Haz que tus archivos funcionen mejor.", description: "Herramientas prácticas para PDF, imágenes, SVG e iconos, con archivos cerca y resultados claros.", primary: "Ver herramientas", secondary: "Cómo funciona la privacidad", featured: "Empieza con una tarea real", featuredDescription: "Cuatro espacios de trabajo para terminar lo que necesitas.", workflow: "Un flujo de archivos más tranquilo", workflowDescription: "Elige una tarea, añade un archivo y comprueba el resultado. Sin cuenta ni colas opacas.", privacyTitle: "Tus archivos siguen siendo tuyos.", privacyDescription: "Las herramientas del navegador procesan localmente. Las herramientas de servidor piden permiso y limpian los resultados en 15 minutos.", browse: "Ver todas" }, workspace: { dropTitle: "Suelta los archivos aquí", dropDescription: "o elígelos desde este dispositivo. El procesamiento empieza al pulsar el botón.", choose: "Elegir archivos", process: "Procesar archivos", clear: "Borrar todo", remove: "Quitar", waiting: "En espera", working: "Procesando", ready: "Listo para descargar", failed: "No se pudo procesar", local: "Local", server: "Servidor", hybrid: "Subida con permiso", format: "Formato", size: "Tamaño", output: "Salida", consent: "Entiendo que este archivo se subirá para esta tarea.", serverConsent: "El procesamiento en servidor necesita tu permiso.", download: "Descargar", noFiles: "Añade al menos un archivo para empezar." }, category: { pdf: "Herramientas PDF", image: "Herramientas de imagen", svg: "Herramientas SVG", icons: "Herramientas de iconos" }, common: { steps: "Cómo funciona", limits: "Límites y compatibilidad", privacy: "Nota de privacidad", related: "Continúa con", faq: "Preguntas frecuentes", input: "Entrada", output: "Salida", honest: "Comprobamos la salida. Si la compresión no ahorra espacio, se conserva el original.", notFound: "Esta página no existe." } },
  de: { nav: { tools: "Werkzeuge", guides: "Anleitungen", privacy: "Datenschutz", about: "Über uns" }, home: { eyebrow: "Lokale Dateiverarbeitung", title: "Dateien besser nutzen.", description: "Praktische PDF-, Bild-, SVG- und Icon-Werkzeuge mit nachvollziehbaren Ergebnissen.", primary: "Werkzeuge ansehen", secondary: "Datenschutz verstehen", featured: "Mit einer echten Aufgabe starten", featuredDescription: "Vier fokussierte Arbeitsbereiche für den Alltag.", workflow: "Ein ruhigerer Dateifluss", workflowDescription: "Aufgabe wählen, Datei hinzufügen, Ergebnis prüfen. Ohne Konto und ohne undurchsichtige Warteschlange.", privacyTitle: "Deine Dateien bleiben deine Dateien.", privacyDescription: "Browser-Werkzeuge verarbeiten lokal. Server-Werkzeuge fragen vorher und löschen Ergebnisse nach 15 Minuten.", browse: "Alle ansehen" }, workspace: { dropTitle: "Dateien hier ablegen", dropDescription: "oder Dateien von diesem Gerät wählen. Die Verarbeitung beginnt erst per Klick.", choose: "Dateien wählen", process: "Dateien verarbeiten", clear: "Alle löschen", remove: "Entfernen", waiting: "Wartet", working: "Verarbeitung", ready: "Bereit zum Download", failed: "Verarbeitung fehlgeschlagen", local: "Lokal", server: "Server", hybrid: "Upload mit Zustimmung", format: "Format", size: "Größe", output: "Ausgabe", consent: "Ich stimme dem Upload für diese Aufgabe zu.", serverConsent: "Serververarbeitung braucht deine ausdrückliche Zustimmung.", download: "Download", noFiles: "Füge mindestens eine Datei hinzu." }, category: { pdf: "PDF-Werkzeuge", image: "Bild-Werkzeuge", svg: "SVG-Werkzeuge", icons: "Icon-Werkzeuge" }, common: { steps: "So funktioniert es", limits: "Grenzen und Support", privacy: "Datenschutzhinweis", related: "Weiter mit", faq: "Häufige Fragen", input: "Eingabe", output: "Ausgabe", honest: "Die Ausgabe wird geprüft. Wenn Komprimierung keinen Platz spart, bleibt das Original erhalten.", notFound: "Diese Seite gibt es nicht." } },
  fr: { nav: { tools: "Outils", guides: "Guides", privacy: "Confidentialité", about: "À propos" }, home: { eyebrow: "Traitement local", title: "Des fichiers plus simples à utiliser.", description: "Des outils PDF, image, SVG et icône pratiques, avec des résultats vérifiables.", primary: "Voir les outils", secondary: "Comprendre la confidentialité", featured: "Commencer par une vraie tâche", featuredDescription: "Quatre espaces de travail pour aller au bout du travail.", workflow: "Un flux de fichiers plus serein", workflowDescription: "Choisissez une tâche, ajoutez un fichier, vérifiez le résultat. Sans compte ni file opaque.", privacyTitle: "Vos fichiers restent les vôtres.", privacyDescription: "Les outils du navigateur traitent localement. Les outils serveur demandent votre accord et suppriment les résultats après 15 minutes.", browse: "Tout voir" }, workspace: { dropTitle: "Déposez les fichiers ici", dropDescription: "ou choisissez-les sur cet appareil. Le traitement commence au clic.", choose: "Choisir des fichiers", process: "Traiter les fichiers", clear: "Tout effacer", remove: "Retirer", waiting: "En attente", working: "Traitement", ready: "Prêt à télécharger", failed: "Échec du traitement", local: "Local", server: "Serveur", hybrid: "Envoi avec accord", format: "Format", size: "Taille", output: "Sortie", consent: "J’accepte l’envoi de ce fichier pour cette tâche.", serverConsent: "Le traitement serveur nécessite votre accord explicite.", download: "Télécharger", noFiles: "Ajoutez au moins un fichier pour commencer." }, category: { pdf: "Outils PDF", image: "Outils image", svg: "Outils SVG", icons: "Outils d’icônes" }, common: { steps: "Mode d’emploi", limits: "Limites et compatibilité", privacy: "Note de confidentialité", related: "Continuer avec", faq: "Questions fréquentes", input: "Entrée", output: "Sortie", honest: "La sortie est vérifiée. Si la compression n’économise rien, l’original est conservé.", notFound: "Cette page n’existe pas." } },
  ja: { nav: { tools: "ツール", guides: "ガイド", privacy: "プライバシー", about: "概要" }, home: { eyebrow: "ローカル優先のファイル処理", title: "ファイルを、もっと使いやすく。", description: "PDF、画像、SVG、アイコンを扱う実用的なツール。結果を確認でき、ファイルは手元に保てます。", primary: "ツールを見る", secondary: "プライバシーについて", featured: "実際の作業から始める", featuredDescription: "日々のファイル作業を終えるための4つのワークスペース。", workflow: "落ち着いたファイルの流れ", workflowDescription: "作業を選び、ファイルを追加し、結果を確認。アカウントも不透明な待ち行列も不要です。", privacyTitle: "ファイルは、基本的にあなたのもの。", privacyDescription: "ブラウザツールはローカルで処理します。サーバーツールはアップロード前に説明と同意を求め、15分後に結果を削除します。", browse: "すべて見る" }, workspace: { dropTitle: "ここにファイルをドロップ", dropDescription: "またはこのデバイスから選択。ボタンを押すまで処理は始まりません。", choose: "ファイルを選択", process: "ファイルを処理", clear: "すべて消去", remove: "削除", waiting: "待機中", working: "処理中", ready: "ダウンロード可能", failed: "処理できませんでした", local: "ローカル", server: "サーバー", hybrid: "同意後にアップロード", format: "形式", size: "サイズ", output: "出力", consent: "この作業でファイルがアップロードされることを理解しました。", serverConsent: "サーバー処理には明示的な同意が必要です。", download: "ダウンロード", noFiles: "まずファイルを1つ以上追加してください。" }, category: { pdf: "PDF ツール", image: "画像ツール", svg: "SVG ツール", icons: "アイコンツール" }, common: { steps: "使い方", limits: "制限と対応", privacy: "プライバシーについて", related: "次に使う", faq: "よくある質問", input: "入力", output: "出力", honest: "出力を確認します。圧縮しても小さくならない場合は元ファイルを保持します。", notFound: "このページは存在しません。" } },
};

translations["pt-BR"] = { nav: { tools: "Ferramentas", guides: "Guias", privacy: "Privacidade", about: "Sobre" }, home: { eyebrow: "Processamento local", title: "Arquivos mais fáceis de usar.", description: "Ferramentas práticas para PDF, imagens, SVG e ícones, com resultados claros.", primary: "Ver ferramentas", secondary: "Como funciona a privacidade", featured: "Comece com uma tarefa real", featuredDescription: "Quatro espaços de trabalho para concluir o que importa.", workflow: "Um fluxo de arquivos mais tranquilo", workflowDescription: "Escolha uma tarefa, adicione um arquivo e confira o resultado. Sem conta e sem fila opaca.", privacyTitle: "Seus arquivos continuam sendo seus.", privacyDescription: "As ferramentas do navegador processam localmente. As ferramentas de servidor pedem consentimento e limpam os resultados em 15 minutos.", browse: "Ver todos" }, workspace: { dropTitle: "Solte os arquivos aqui", dropDescription: "ou escolha arquivos deste dispositivo. O processamento começa somente ao clicar no botão.", choose: "Escolher arquivos", process: "Processar arquivos", clear: "Limpar tudo", remove: "Remover", waiting: "Aguardando", working: "Processando", ready: "Pronto para baixar", failed: "Não foi possível processar", local: "Local", server: "Servidor", hybrid: "Upload com consentimento", format: "Formato", size: "Tamanho", output: "Saída", consent: "Entendo que este arquivo será enviado para esta tarefa.", serverConsent: "O processamento no servidor exige seu consentimento explícito.", download: "Baixar", noFiles: "Adicione pelo menos um arquivo para começar." }, category: { pdf: "Ferramentas PDF", image: "Ferramentas de imagem", svg: "Ferramentas SVG", icons: "Ferramentas de ícones" }, common: { steps: "Como funciona", limits: "Limites e suporte", privacy: "Nota de privacidade", related: "Continue com", faq: "Perguntas comuns", input: "Entrada", output: "Saída", honest: "A saída é verificada. Se a compressão não economizar espaço, o original é mantido.", notFound: "Esta página não existe." } };

function mergeMessages(base: Messages, override?: Partial<Messages>): Messages {
  return { ...base, ...override, nav: { ...base.nav, ...override?.nav }, home: { ...base.home, ...override?.home }, workspace: { ...base.workspace, ...override?.workspace }, category: { ...base.category, ...override?.category }, common: { ...base.common, ...override?.common } };
}

export function isLocale(value: string): value is Locale { return (LOCALES as readonly string[]).includes(value); }
export function getMessages(locale: Locale): Messages { return mergeMessages(en, translations[locale]); }
export function getCancelLabel(locale: Locale): string { return ({ ...expandedMap(c => c.status.cancel), ko: "취소", it: "Annulla", en: "Cancel", "zh-CN": "取消", "zh-TW": "取消", es: "Cancelar", "pt-BR": "Cancelar", de: "Abbrechen", fr: "Annuler", ja: "キャンセル" } as Record<Locale, string>)[locale]; }
export function getStatusLabel(locale: Locale, status: "cancelled"): string { return ({ ...expandedMap(c => c.status.cancelled), ko: "취소됨", it: "Annullato", en: "Cancelled", "zh-CN": "已取消", "zh-TW": "已取消", es: "Cancelado", "pt-BR": "Cancelado", de: "Abgebrochen", fr: "Annulé", ja: "キャンセル済み" } as Record<Locale, string>)[locale]; }
export function getLocalePath(locale: Locale, path = ""): string { return `/${locale}${path.startsWith("/") || !path ? path : `/${path}`}`; }

export type PageCopy = {
  about: { title: string; intro: string; whatTitle: string; whatBody: string; limitsTitle: string; limitsBody: string };
  privacy: { title: string; intro: string; serverTitle: string; serverBody: string; retainedTitle: string; retainedBody: string; limitsTitle: string; limitsBody: string };
  terms: { title: string; intro: string; boundaryTitle: string; boundaryBody: string; fairTitle: string; fairBody: string };
  contact: { title: string; intro: string; missing: string };
  tool: { intro: string; stepsTitle: string; addTitle: string; addBody: string; optionsTitle: string; optionsBody: string; checkTitle: string; checkBody: string; limitsTitle: string; privacyTitle: string; localPrivacy: string; serverPrivacy: string; relatedIntro: string };
};

const basePageCopy: PageCopy = {
  about: { title: "About HXSL Tools", intro: "HXSL Tools is a small, configurable collection of file utilities for creators and developers. It favors browser-local work, explicit boundaries and outputs you can inspect.", whatTitle: "What we build", whatBody: "PDF, image, SVG and icon tasks with crawlable instructions, practical limits and a clear distinction between local and server processing.", limitsTitle: "What we do not claim", limitsBody: "Image signatures are appearances, not cryptographic signatures. OCR is approximate. SVG tracing is reconstruction. Office layout depends on LibreOffice and installed fonts. Read each task’s support note before relying on its output." },
  privacy: { title: "Your file stays close.", intro: "HXSL Tools is designed for local-first processing. A browser task uses the selected file in the current page. It does not upload automatically, write file content to localStorage, or send file bytes to analytics.", serverTitle: "Server tasks", serverBody: "Tasks labelled server or hybrid require a visible consent choice before upload. A job receives an unpredictable identifier and a separate authorization token. Inputs and results live in protected temporary directories, are not placed in public static files, and are scheduled for cleanup after 15 minutes by default. Cancellation and deletion clean the job immediately.", retainedTitle: "What is retained", retainedBody: "The build keeps only short-lived job metadata needed to process and download a result. Passwords and file contents are not written to logs. No analytics SDK is loaded by default. Operators can change limits and retention through environment configuration.", limitsTitle: "Limits of the promise", limitsBody: "Temporary deletion describes application lifecycle management, not independently verifiable physical erasure from storage. Always review sensitive files before sharing." },
  terms: { title: "Terms of use", intro: "Use HXSL Tools only with files you are allowed to process. You are responsible for checking outputs, licenses, permissions, and any legal or compliance requirements that apply to your documents.", boundaryTitle: "Service boundaries", boundaryBody: "Tools provide the capabilities and limits stated on their pages. They do not guarantee OCR accuracy, visual fidelity, legal effect, signature trust, compatibility with every device, or preservation of complex document features.", fairTitle: "Fair use", fairBody: "Do not use the service to abuse infrastructure, bypass document access controls, or process content unlawfully. Server access can be limited for safety." },
  contact: { title: "Contact", intro: "For support, accessibility notes, security reports or localization corrections, use the configured operator contact.", missing: "CONTACT_EMAIL is not configured in this environment. Add a real operator address before production launch." },
  tool: { intro: "This page explains the task, limits and processing boundary in the initial HTML. The file workbench starts only when you choose a file.", stepsTitle: "How it works", addTitle: "01 / Add the input", addBody: "Choose a supported file or drop it into the workbench. We validate the selected format before processing.", optionsTitle: "02 / Set the useful options", optionsBody: "Use the controls only when this task needs them. Limits apply to decoded pixels, files, pages and output size, not just the extension.", checkTitle: "03 / Check and download", checkBody: "Each result is independently marked ready or failed. Downloads are created from the current session and are not kept after a refresh.", limitsTitle: "Limits and support", privacyTitle: "Privacy note", localPrivacy: "This task is local-first. The browser processes the selected file and no upload fallback runs automatically.", serverPrivacy: "This task needs a server engine in the current build. The workbench requires an explicit consent check before upload; results are temporary and removed after the configured TTL.", relatedIntro: "Keep the same file thread moving with a related task." },
};

const pageTranslations: Partial<Record<Locale, Partial<PageCopy>>> = {
  ...packMap(c => c.page),
  ko: additionalLocales.ko.page, it: additionalLocales.it.page,

  "zh-CN": {
    about: { title: "关于 HXSL Tools", intro: "HXSL Tools 是面向创作者和开发者的小型可配置文件工具集，优先在浏览器本地处理，并清楚说明处理边界与可检查的输出。", whatTitle: "我们提供什么", whatBody: "PDF、图片、SVG 和图标任务，包含可抓取的说明、实际限制，并明确区分本地处理与服务端处理。", limitsTitle: "我们不做什么保证", limitsBody: "图片签名只是外观，不是密码学签名。OCR 结果是近似的。SVG 描摹是重建。Office 排版取决于 LibreOffice 和安装的字体。依赖输出前请阅读对应任务的支持说明。" },
    privacy: { title: "文件尽量留在你手边", intro: "HXSL Tools 按本地优先设计。浏览器任务只在当前页面使用所选文件，不会自动上传，不会把文件内容写入 localStorage，也不会把文件字节发送给分析服务。", serverTitle: "服务端任务", serverBody: "标记为服务端或混合模式的任务会在上传前显示同意选项。任务使用不可预测的 ID 和独立授权 token。输入和结果位于受保护的临时目录，默认 15 分钟后清理；取消和删除会立即清理。", retainedTitle: "保留什么", retainedBody: "系统只保留处理和下载结果所需的短期任务元数据。密码和文件内容不会写入日志，默认不加载分析 SDK。运营者可以通过环境配置调整限制和保留时间。", limitsTitle: "承诺的边界", limitsBody: "临时删除代表应用生命周期管理，不代表可独立验证的物理存储擦除。分享敏感文件前请自行检查。" },
    terms: { title: "使用条款", intro: "仅使用你有权处理的文件。你需要自行检查输出、许可证、权限以及适用于文档的法律或合规要求。", boundaryTitle: "服务边界", boundaryBody: "工具只提供页面声明的能力和限制，不保证 OCR 准确率、视觉还原、法律效力、签名信任、所有设备兼容性或复杂文档特性的保留。", fairTitle: "合理使用", fairBody: "不得滥用基础设施、绕过文档访问控制或违法处理内容。出于安全原因，服务端访问可能受到限制。" },
    contact: { title: "联系", intro: "如需支持、反馈无障碍问题、报告安全问题或修正翻译，请使用配置的运营者联系方式。", missing: "当前环境未配置 CONTACT_EMAIL。正式上线前请添加真实的运营者邮箱。" },
    tool: { intro: "本页的任务、限制和处理边界会出现在初始 HTML 中。只有选择文件后，工作台才会开始处理。", stepsTitle: "使用步骤", addTitle: "01 / 添加输入", addBody: "选择支持的文件或拖入工作台。处理前会先验证所选格式。", optionsTitle: "02 / 设置必要选项", optionsBody: "只在任务需要时使用这些控件。限制不仅针对扩展名，也包括解码像素、文件数、页数和输出大小。", checkTitle: "03 / 检查并下载", checkBody: "每个结果都会单独标记为可用或失败。下载来自当前会话，刷新后不会继续保留。", limitsTitle: "限制与支持", privacyTitle: "隐私说明", localPrivacy: "此任务优先在本地处理。浏览器会处理所选文件，不会自动回退上传。", serverPrivacy: "当前构建需要服务端引擎。上传前工作台会要求明确同意；结果是临时的，并在配置的 TTL 后清理。", relatedIntro: "用相关任务继续处理同一份文件。" },
  },
  "zh-TW": {
    about: { title: "關於 HXSL Tools", intro: "HXSL Tools 是為創作者與開發者提供的小型可設定檔案工具集，優先在瀏覽器本機處理，並清楚說明處理邊界與可檢查的輸出。", whatTitle: "我們提供什麼", whatBody: "PDF、圖片、SVG 與圖示任務，包含可抓取的說明、實際限制，並明確區分本機與伺服器處理。", limitsTitle: "我們不保證什麼", limitsBody: "圖片簽名只是外觀，不是密碼學簽名。OCR 是近似結果。SVG 描摹是重建。Office 排版取決於 LibreOffice 與安裝字型。依賴輸出前請閱讀任務支援說明。" },
    privacy: { title: "檔案盡量留在你手邊", intro: "HXSL Tools 以本機優先設計。瀏覽器任務只在目前頁面使用所選檔案，不會自動上傳、不會把檔案內容寫入 localStorage，也不會把檔案位元組傳給分析服務。", serverTitle: "伺服器任務", serverBody: "標記為伺服器或混合模式的任務會在上傳前顯示同意選項。任務使用不可預測的 ID 與獨立授權 token。輸入與結果位於受保護的暫存目錄，預設 15 分鐘後清理；取消與刪除會立即清理。", retainedTitle: "保留什麼", retainedBody: "系統只保留處理與下載結果所需的短期任務中繼資料。密碼與檔案內容不會寫入日誌，預設不載入分析 SDK。營運者可透過環境設定調整限制與保留時間。", limitsTitle: "承諾的邊界", limitsBody: "暫存刪除代表應用程式生命週期管理，不代表可獨立驗證的實體儲存抹除。分享敏感檔案前請自行檢查。" },
    terms: { title: "使用條款", intro: "只使用你有權處理的檔案。你需要自行檢查輸出、授權、權限以及適用於文件的法律或合規要求。", boundaryTitle: "服務邊界", boundaryBody: "工具只提供頁面聲明的能力與限制，不保證 OCR 準確率、視覺還原、法律效力、簽名信任、所有裝置相容性或複雜文件特性的保留。", fairTitle: "合理使用", fairBody: "不得濫用基礎設施、繞過文件存取控制或違法處理內容。基於安全原因，伺服器存取可能受到限制。" },
    contact: { title: "聯絡", intro: "如需支援、回報無障礙問題、安全問題或翻譯修正，請使用已設定的營運者聯絡方式。", missing: "目前環境未設定 CONTACT_EMAIL。正式上線前請加入真實營運者信箱。" },
    tool: { intro: "本頁的任務、限制與處理邊界會出現在初始 HTML 中。選擇檔案後工作台才會開始處理。", stepsTitle: "使用步驟", addTitle: "01 / 加入輸入", addBody: "選擇支援的檔案或拖入工作台。處理前會先驗證所選格式。", optionsTitle: "02 / 設定必要選項", optionsBody: "只在任務需要時使用這些控制項。限制也包括解碼像素、檔案數、頁數與輸出大小，而不只是副檔名。", checkTitle: "03 / 檢查並下載", checkBody: "每個結果會單獨標記為可用或失敗。下載來自目前工作階段，重新整理後不會繼續保留。", limitsTitle: "限制與支援", privacyTitle: "隱私說明", localPrivacy: "此任務優先在本機處理。瀏覽器會處理所選檔案，不會自動回退上傳。", serverPrivacy: "目前版本需要伺服器引擎。上傳前工作台會要求明確同意；結果是暫時的，並在設定的 TTL 後清理。", relatedIntro: "使用相關任務繼續處理同一份檔案。" },
  },
  es: {
    about: { title: "Acerca de HXSL Tools", intro: "HXSL Tools es una colección pequeña y configurable de utilidades para archivos, pensada para creadores y desarrolladores. Favorece el trabajo local en el navegador y resultados que puedes revisar.", whatTitle: "Lo que construimos", whatBody: "Tareas para PDF, imágenes, SVG e iconos con instrucciones rastreables, límites prácticos y una distinción clara entre procesamiento local y de servidor.", limitsTitle: "Lo que no afirmamos", limitsBody: "Las firmas de imagen son solo apariencias, no firmas criptográficas. El OCR es aproximado. El trazado SVG es una reconstrucción. La maquetación de Office depende de LibreOffice y de las fuentes instaladas." },
    privacy: { title: "Tus archivos siguen cerca", intro: "HXSL Tools está diseñado para procesar primero en local. Una tarea del navegador usa el archivo seleccionado en la página actual, sin subirlo automáticamente ni enviarlo a analítica.", serverTitle: "Tareas de servidor", serverBody: "Las tareas de servidor o híbridas muestran un consentimiento antes de subir. Las entradas y resultados viven en directorios temporales protegidos y se limpian después de 15 minutos por defecto. Cancelar o borrar limpia la tarea de inmediato.", retainedTitle: "Qué se conserva", retainedBody: "Solo se conserva la metadata temporal necesaria para procesar y descargar un resultado. Las contraseñas y el contenido no se escriben en los registros y no se carga un SDK de analítica por defecto.", limitsTitle: "Límites de la promesa", limitsBody: "La eliminación temporal describe el ciclo de vida de la aplicación, no un borrado físico verificable del almacenamiento." },
    terms: { title: "Condiciones de uso", intro: "Usa HXSL Tools solo con archivos que tengas permiso para procesar. Debes comprobar los resultados, licencias, permisos y requisitos legales aplicables.", boundaryTitle: "Límites del servicio", boundaryBody: "Las herramientas no garantizan la precisión del OCR, la fidelidad visual, el efecto legal, la confianza de una firma, la compatibilidad con todos los dispositivos ni la conservación de funciones complejas.", fairTitle: "Uso razonable", fairBody: "No abuses de la infraestructura, evites controles de acceso ni proceses contenido ilegalmente. El acceso de servidor puede limitarse por seguridad." },
    contact: { title: "Contacto", intro: "Para soporte, accesibilidad, informes de seguridad o correcciones de traducción, usa el contacto del operador configurado.", missing: "CONTACT_EMAIL no está configurado. Añade una dirección real antes del lanzamiento." },
    tool: { intro: "Esta página explica la tarea, sus límites y su frontera de procesamiento en el HTML inicial. El espacio de trabajo comienza al elegir un archivo.", stepsTitle: "Cómo funciona", addTitle: "01 / Añade la entrada", addBody: "Elige un archivo compatible o suéltalo en el espacio de trabajo. Validamos el formato antes de procesar.", optionsTitle: "02 / Ajusta las opciones útiles", optionsBody: "Usa los controles solo cuando la tarea los necesite. Los límites cubren píxeles decodificados, archivos, páginas y tamaño de salida.", checkTitle: "03 / Comprueba y descarga", checkBody: "Cada resultado se marca de forma independiente como listo o fallido. Las descargas pertenecen a la sesión actual y no se conservan tras recargar.", limitsTitle: "Límites y compatibilidad", privacyTitle: "Nota de privacidad", localPrivacy: "Esta tarea prioriza el procesamiento local. El navegador procesa el archivo y no activa una subida automática.", serverPrivacy: "Esta tarea necesita un motor de servidor. Se requiere consentimiento explícito antes de subir y los resultados se eliminan tras el TTL configurado.", relatedIntro: "Continúa con una tarea relacionada usando el mismo archivo." },
  },
  de: {
    about: { title: "Über HXSL Tools", intro: "HXSL Tools ist eine kleine, konfigurierbare Sammlung von Dateiverarbeitungswerkzeugen für Kreative und Entwickler. Die Verarbeitung im Browser und überprüfbare Ausgaben stehen im Vordergrund.", whatTitle: "Was wir bauen", whatBody: "PDF-, Bild-, SVG- und Icon-Aufgaben mit crawlbaren Anleitungen, praktischen Grenzen und einer klaren Trennung zwischen lokaler und serverseitiger Verarbeitung.", limitsTitle: "Was wir nicht versprechen", limitsBody: "Bildsignaturen sind Darstellungen, keine kryptografischen Signaturen. OCR ist eine Näherung. SVG-Nachzeichnen ist eine Rekonstruktion. Office-Layout hängt von LibreOffice und installierten Schriften ab." },
    privacy: { title: "Deine Dateien bleiben nah bei dir", intro: "HXSL Tools ist auf lokale Verarbeitung ausgelegt. Eine Browser-Aufgabe verwendet die ausgewählte Datei auf der aktuellen Seite, lädt sie nicht automatisch hoch und sendet keine Dateibytes an Analysen.", serverTitle: "Serveraufgaben", serverBody: "Server- oder Hybridaufgaben verlangen vor dem Upload eine sichtbare Zustimmung. Eingaben und Ergebnisse liegen in geschützten temporären Verzeichnissen und werden standardmäßig nach 15 Minuten gelöscht.", retainedTitle: "Was gespeichert wird", retainedBody: "Nur kurzlebige Metadaten für Verarbeitung und Download werden behalten. Passwörter und Dateiinhalte landen nicht in Logs; standardmäßig wird kein Analyse-SDK geladen.", limitsTitle: "Grenzen des Versprechens", limitsBody: "Temporäres Löschen beschreibt den Anwendungslebenszyklus, nicht eine unabhängig prüfbare physische Löschung." },
    terms: { title: "Nutzungsbedingungen", intro: "Verwende HXSL Tools nur mit Dateien, die du verarbeiten darfst. Du bist für die Prüfung von Ergebnissen, Lizenzen, Berechtigungen und rechtlichen Anforderungen verantwortlich.", boundaryTitle: "Servicegrenzen", boundaryBody: "Die Werkzeuge garantieren weder OCR-Genauigkeit, visuelle Treue, rechtliche Wirkung, Signaturvertrauen, Gerätekompatibilität noch die Erhaltung komplexer Dokumentfunktionen.", fairTitle: "Faire Nutzung", fairBody: "Missbrauche die Infrastruktur nicht, umgehe keine Zugriffskontrollen und verarbeite keine rechtswidrigen Inhalte. Serverzugriff kann aus Sicherheitsgründen begrenzt werden." },
    contact: { title: "Kontakt", intro: "Für Support, Barrierefreiheit, Sicherheitsmeldungen oder Übersetzungskorrekturen nutze den konfigurierten Betreiberkontakt.", missing: "CONTACT_EMAIL ist nicht konfiguriert. Vor dem Start muss eine echte Betreiberadresse ergänzt werden." },
    tool: { intro: "Diese Seite erklärt Aufgabe, Grenzen und Verarbeitungsgrenze bereits im initialen HTML. Die Arbeitsfläche startet erst nach der Dateiauswahl.", stepsTitle: "So funktioniert es", addTitle: "01 / Eingabe hinzufügen", addBody: "Wähle eine unterstützte Datei oder ziehe sie in die Arbeitsfläche. Das Format wird vor der Verarbeitung geprüft.", optionsTitle: "02 / Sinnvolle Optionen setzen", optionsBody: "Nutze Optionen nur, wenn diese Aufgabe sie benötigt. Grenzen gelten für dekodierte Pixel, Dateien, Seiten und Ausgabegröße.", checkTitle: "03 / Prüfen und herunterladen", checkBody: "Jedes Ergebnis wird einzeln als bereit oder fehlgeschlagen markiert. Downloads gehören zur aktuellen Sitzung und werden nach dem Neuladen nicht behalten.", limitsTitle: "Grenzen und Support", privacyTitle: "Datenschutzhinweis", localPrivacy: "Diese Aufgabe verarbeitet lokal zuerst. Der Browser verarbeitet die Datei; ein Upload-Fallback startet nicht automatisch.", serverPrivacy: "Diese Aufgabe benötigt eine Server-Engine. Vor dem Upload ist eine ausdrückliche Zustimmung nötig; Ergebnisse werden nach dem konfigurierten TTL gelöscht.", relatedIntro: "Mit einer verwandten Aufgabe am selben Dateifluss weiterarbeiten." },
  },
  fr: {
    about: { title: "À propos de HXSL Tools", intro: "HXSL Tools est une collection configurable d’outils de fichiers pour les créateurs et les développeurs. Le traitement local et des résultats vérifiables sont prioritaires.", whatTitle: "Ce que nous construisons", whatBody: "Des tâches PDF, image, SVG et icône avec des instructions indexables, des limites concrètes et une séparation claire entre traitement local et serveur.", limitsTitle: "Ce que nous ne promettons pas", limitsBody: "Les signatures d’image sont des apparences, pas des signatures cryptographiques. L’OCR est approximatif. Le tracé SVG est une reconstruction. La mise en page Office dépend de LibreOffice et des polices installées." },
    privacy: { title: "Vos fichiers restent près de vous", intro: "HXSL Tools privilégie le traitement local. Une tâche du navigateur utilise le fichier choisi dans la page courante, sans envoi automatique ni transmission des octets à l’analytique.", serverTitle: "Tâches serveur", serverBody: "Les tâches serveur ou hybrides demandent un consentement visible avant l’envoi. Les entrées et résultats sont stockés dans des répertoires temporaires protégés et supprimés après 15 minutes par défaut.", retainedTitle: "Ce qui est conservé", retainedBody: "Seules les métadonnées temporaires nécessaires au traitement et au téléchargement sont conservées. Les mots de passe et contenus ne sont pas consignés et aucun SDK analytique n’est chargé par défaut.", limitsTitle: "Limites de la promesse", limitsBody: "La suppression temporaire décrit le cycle de vie de l’application, pas un effacement physique vérifiable du stockage." },
    terms: { title: "Conditions d’utilisation", intro: "Utilisez HXSL Tools uniquement avec des fichiers que vous êtes autorisé à traiter. Vous devez vérifier les résultats, licences, autorisations et obligations applicables.", boundaryTitle: "Limites du service", boundaryBody: "Les outils ne garantissent ni la précision OCR, ni la fidélité visuelle, ni l’effet juridique, ni la confiance d’une signature, ni la compatibilité universelle ou la conservation des fonctions complexes.", fairTitle: "Usage raisonnable", fairBody: "N’abusez pas de l’infrastructure, ne contournez pas les contrôles d’accès et ne traitez pas de contenu illicite. L’accès serveur peut être limité pour la sécurité." },
    contact: { title: "Contact", intro: "Pour le support, l’accessibilité, les alertes de sécurité ou les corrections de traduction, utilisez le contact opérateur configuré.", missing: "CONTACT_EMAIL n’est pas configuré. Ajoutez une adresse réelle avant la mise en production." },
    tool: { intro: "Cette page présente la tâche, ses limites et sa frontière de traitement dans le HTML initial. L’espace de travail démarre lorsque vous choisissez un fichier.", stepsTitle: "Mode d’emploi", addTitle: "01 / Ajouter l’entrée", addBody: "Choisissez un fichier pris en charge ou déposez-le dans l’espace de travail. Le format est vérifié avant le traitement.", optionsTitle: "02 / Régler les options utiles", optionsBody: "Utilisez les contrôles seulement si la tâche le demande. Les limites concernent les pixels décodés, les fichiers, les pages et la taille de sortie.", checkTitle: "03 / Vérifier et télécharger", checkBody: "Chaque résultat est marqué séparément comme prêt ou échoué. Les téléchargements appartiennent à la session courante et ne sont pas conservés après actualisation.", limitsTitle: "Limites et compatibilité", privacyTitle: "Note de confidentialité", localPrivacy: "Cette tâche privilégie le local. Le navigateur traite le fichier et aucun envoi de secours ne démarre automatiquement.", serverPrivacy: "Cette tâche nécessite un moteur serveur. Un consentement explicite est requis avant l’envoi et les résultats sont supprimés après le TTL configuré.", relatedIntro: "Poursuivez le même flux de fichier avec une tâche associée." },
  },
  "pt-BR": {
    about: { title: "Sobre o HXSL Tools", intro: "HXSL Tools é uma coleção pequena e configurável de ferramentas para arquivos, criada para profissionais criativos e desenvolvedores. Priorizamos o processamento no navegador e resultados que você pode verificar.", whatTitle: "O que criamos", whatBody: "Tarefas para PDF, imagens, SVG e ícones com instruções indexáveis, limites práticos e uma separação clara entre processamento local e no servidor.", limitsTitle: "O que não prometemos", limitsBody: "Assinaturas de imagem são aparências, não assinaturas criptográficas. OCR é aproximado. A vetorização SVG é uma reconstrução. O layout do Office depende do LibreOffice e das fontes instaladas." },
    privacy: { title: "Seus arquivos ficam por perto", intro: "O HXSL Tools foi projetado para priorizar o processamento local. Uma tarefa do navegador usa o arquivo selecionado na página atual, sem upload automático ou envio dos bytes para análise.", serverTitle: "Tarefas no servidor", serverBody: "Tarefas de servidor ou híbridas pedem consentimento visível antes do upload. Entradas e resultados ficam em diretórios temporários protegidos e são removidos por padrão após 15 minutos.", retainedTitle: "O que é mantido", retainedBody: "Apenas metadados temporários necessários para processar e baixar o resultado são mantidos. Senhas e conteúdo não vão para os logs, e nenhum SDK de análise é carregado por padrão.", limitsTitle: "Limites da promessa", limitsBody: "A remoção temporária descreve o ciclo de vida da aplicação, não uma eliminação física verificável do armazenamento." },
    terms: { title: "Termos de uso", intro: "Use o HXSL Tools somente com arquivos que você pode processar. Você é responsável por verificar resultados, licenças, permissões e requisitos legais aplicáveis.", boundaryTitle: "Limites do serviço", boundaryBody: "As ferramentas não garantem precisão de OCR, fidelidade visual, efeito jurídico, confiança de assinatura, compatibilidade com todos os dispositivos ou preservação de recursos complexos.", fairTitle: "Uso justo", fairBody: "Não abuse da infraestrutura, não contorne controles de acesso e não processe conteúdo ilegal. O acesso ao servidor pode ser limitado por segurança." },
    contact: { title: "Contato", intro: "Para suporte, acessibilidade, relatos de segurança ou correções de tradução, use o contato do operador configurado.", missing: "CONTACT_EMAIL não está configurado. Adicione um endereço real antes do lançamento." },
    tool: { intro: "Esta página explica a tarefa, seus limites e sua fronteira de processamento no HTML inicial. O espaço de trabalho começa somente quando você escolhe um arquivo.", stepsTitle: "Como funciona", addTitle: "01 / Adicione a entrada", addBody: "Escolha um arquivo compatível ou solte-o no espaço de trabalho. O formato é validado antes do processamento.", optionsTitle: "02 / Ajuste as opções úteis", optionsBody: "Use os controles somente quando a tarefa precisar deles. Os limites cobrem pixels decodificados, arquivos, páginas e tamanho da saída.", checkTitle: "03 / Confira e baixe", checkBody: "Cada resultado é marcado separadamente como pronto ou com falha. Os downloads pertencem à sessão atual e não são mantidos após atualizar a página.", limitsTitle: "Limites e compatibilidade", privacyTitle: "Nota de privacidade", localPrivacy: "Esta tarefa prioriza o processamento local. O navegador processa o arquivo e não inicia um upload automaticamente.", serverPrivacy: "Esta tarefa precisa de um mecanismo de servidor. O consentimento explícito é necessário antes do upload e os resultados são removidos após o TTL configurado.", relatedIntro: "Continue o fluxo do mesmo arquivo com uma tarefa relacionada." },
  },
  ja: {
    about: { title: "HXSL Tools について", intro: "HXSL Tools はクリエイターと開発者向けの、小さく設定可能なファイルツール集です。ブラウザー内の処理を優先し、境界と確認可能な出力を明確にします。", whatTitle: "提供するもの", whatBody: "PDF、画像、SVG、アイコンのタスクを、検索可能な説明、実用的な制限、ローカル処理とサーバー処理の明確な区別とともに提供します。", limitsTitle: "保証しないこと", limitsBody: "画像の署名は外観であり、暗号学的署名ではありません。OCR は近似結果です。SVG のトレースは再構成です。Office のレイアウトは LibreOffice とインストール済みフォントに依存します。" },
    privacy: { title: "ファイルを手元に保つ", intro: "HXSL Tools はローカル優先で設計されています。ブラウザのタスクは現在のページで選択したファイルを使い、自動アップロードや分析へのファイル送信を行いません。", serverTitle: "サーバータスク", serverBody: "サーバーまたはハイブリッドのタスクは、アップロード前に明示的な同意を求めます。入力と結果は保護された一時ディレクトリに置かれ、標準では15分後に削除されます。", retainedTitle: "保持されるもの", retainedBody: "処理とダウンロードに必要な短期メタデータだけを保持します。パスワードとファイル内容はログに記録せず、分析 SDK も標準では読み込みません。", limitsTitle: "約束の範囲", limitsBody: "一時削除はアプリケーションのライフサイクル管理を示すもので、物理ストレージの消去を独立に証明するものではありません。" },
    terms: { title: "利用規約", intro: "処理する権利のあるファイルだけを使用してください。結果、ライセンス、権限、法令やコンプライアンス要件は利用者が確認します。", boundaryTitle: "サービスの範囲", boundaryBody: "OCR の精度、視覚的な忠実度、法的効果、署名の信頼性、すべての端末との互換性、複雑な文書機能の保持を保証しません。", fairTitle: "適正利用", fairBody: "インフラを悪用したり、アクセス制御を回避したり、違法な内容を処理したりしないでください。安全のためサーバーアクセスを制限する場合があります。" },
    contact: { title: "お問い合わせ", intro: "サポート、アクセシビリティ、安全性の報告、翻訳の修正には、設定済みの運営者連絡先を使用してください。", missing: "CONTACT_EMAIL が設定されていません。本番公開前に実在する運営者アドレスを追加してください。" },
    tool: { intro: "このページではタスク、制限、処理境界を初期 HTML に表示します。ファイルを選ぶまでワークベンチは処理を開始しません。", stepsTitle: "使い方", addTitle: "01 / 入力を追加", addBody: "対応ファイルを選ぶかワークベンチにドロップします。処理前に形式を確認します。", optionsTitle: "02 / 必要なオプションを設定", optionsBody: "タスクに必要な場合だけ操作します。制限は拡張子だけでなく、デコード後のピクセル、ファイル数、ページ数、出力サイズにも適用されます。", checkTitle: "03 / 確認してダウンロード", checkBody: "各結果を個別に成功または失敗として表示します。ダウンロードは現在のセッションに紐づき、更新後は保持されません。", limitsTitle: "制限と対応", privacyTitle: "プライバシーについて", localPrivacy: "このタスクはローカル優先です。ブラウザ内で処理し、自動的なアップロードは行いません。", serverPrivacy: "このタスクにはサーバーエンジンが必要です。アップロード前に明示的な同意を求め、結果は設定された TTL 後に削除します。", relatedIntro: "関連タスクで同じファイルの作業を続けられます。" },
  },
};

function mergePageCopy(locale: Locale): PageCopy { const override = pageTranslations[locale]; return { ...basePageCopy, ...override, about: { ...basePageCopy.about, ...override?.about }, privacy: { ...basePageCopy.privacy, ...override?.privacy }, terms: { ...basePageCopy.terms, ...override?.terms }, contact: { ...basePageCopy.contact, ...override?.contact }, tool: { ...basePageCopy.tool, ...override?.tool } }; }
export function getPageCopy(locale: Locale): PageCopy { return mergePageCopy(locale); }

const categoryDescriptions: Record<Locale, Record<ToolCategory, string>> = {
  ...packMap(c => c.category),
  ko: additionalLocales.ko.category, it: additionalLocales.it.category,

  en: { pdf: "Make precise PDF changes in your browser or with an explicit server task.", image: "Compress and convert images with honest sizes, format checks, and batch controls.", svg: "Create, clean, vectorize, and export SVG with safe parsing and real geometry.", icons: "Export web and Android icon resources with dimensions, previews, and packaging." },
  "zh-CN": { pdf: "在浏览器中精确处理 PDF，或明确选择服务端任务。", image: "压缩和转换图片，显示真实大小、格式检查和批量控制。", svg: "安全解析 SVG，创建、清理、向量化并导出真实几何。", icons: "导出包含尺寸、预览和打包说明的 Web 与 Android 图标资源。" },
  "zh-TW": { pdf: "在瀏覽器中精確處理 PDF，或明確選擇伺服器任務。", image: "壓縮與轉換圖片，顯示真實大小、格式檢查與批次控制。", svg: "安全解析 SVG，建立、清理、向量化並匯出真實幾何。", icons: "匯出包含尺寸、預覽與打包說明的 Web 與 Android 圖示資源。" },
  es: { pdf: "Haz cambios precisos en PDF desde el navegador o con una tarea de servidor explícita.", image: "Comprime y convierte imágenes con tamaños reales, comprobación de formatos y lotes.", svg: "Crea, limpia, vectoriza y exporta SVG con análisis seguro y geometría real.", icons: "Exporta recursos de iconos web y Android con dimensiones, vistas previas y paquetes." },
  "pt-BR": { pdf: "Faça alterações precisas em PDF no navegador ou com uma tarefa de servidor explícita.", image: "Comprima e converta imagens com tamanhos reais, validação de formato e lotes.", svg: "Crie, limpe, vetorize e exporte SVG com análise segura e geometria real.", icons: "Exporte recursos de ícones web e Android com dimensões, prévias e pacotes." },
  de: { pdf: "PDFs präzise im Browser oder mit einer ausdrücklich gewählten Serveraufgabe bearbeiten.", image: "Bilder mit echten Größen, Formatprüfung und Stapelsteuerung komprimieren und umwandeln.", svg: "SVG sicher analysieren, erstellen, bereinigen, vektorisieren und mit echter Geometrie exportieren.", icons: "Web- und Android-Icon-Ressourcen mit Größen, Vorschauen und Paketstruktur exportieren." },
  fr: { pdf: "Modifier précisément des PDF dans le navigateur ou avec une tâche serveur explicite.", image: "Compresser et convertir les images avec tailles réelles, vérification du format et traitement par lots.", svg: "Créer, nettoyer, vectoriser et exporter du SVG avec analyse sûre et géométrie réelle.", icons: "Exporter des ressources d’icônes web et Android avec dimensions, aperçus et emballage." },
  ja: { pdf: "ブラウザー内または明示的に選択したサーバータスクで PDF を正確に処理します。", image: "実際のサイズと形式を確認しながら画像を圧縮・変換できます。", svg: "安全に解析した SVG を作成、整理、ベクター化し、実際の形状として出力します。", icons: "サイズ、プレビュー、パッケージを含む Web と Android のアイコン素材を出力します。" },
};
export function getCategoryDescription(locale: Locale, category: ToolCategory): string { return categoryDescriptions[locale][category]; }

const localizedNameWords: Partial<Record<Locale, Record<string, string>>> = {
  "zh-CN": { Merge: "合并", Split: "拆分", Rotate: "旋转", Reorder: "重新排序", Pages: "页面", Extract: "提取", Delete: "删除", Reverse: "反转", Duplicate: "复制", to: "转", Text: "文本", Word: "Word", Excel: "Excel", PowerPoint: "PowerPoint", Compress: "压缩", Add: "添加", Watermark: "水印", Page: "页", Numbers: "码", Edit: "编辑", Metadata: "元数据", Crop: "裁切", Flatten: "扁平化", Header: "页眉", Footer: "页脚", Sign: "签名", Unlock: "解锁", Protect: "保护", Compare: "比较", Redact: "涂黑", OCR: "OCR", Sanitize: "清理", Verify: "验证", Color: "颜色", Editor: "编辑器", Palette: "调色板", Swapper: "替换器", Optimizer: "优化器", React: "React", Base64: "Base64", Favicon: "网站图标", Pattern: "图案", Maker: "生成器", QR: "二维码", Code: "码", Image: "图片", Resize: "调整尺寸", Background: "背景", Remove: "移除", EXIF: "EXIF", Icon: "图标", Resource: "资源", Pack: "包" },
  "zh-TW": { Merge: "合併", Split: "拆分", Rotate: "旋轉", Reorder: "重新排序", Pages: "頁面", Extract: "擷取", Delete: "刪除", Reverse: "反轉", Duplicate: "複製", to: "轉", Text: "文字", Word: "Word", Excel: "Excel", PowerPoint: "PowerPoint", Compress: "壓縮", Add: "新增", Watermark: "浮水印", Page: "頁", Numbers: "碼", Edit: "編輯", Metadata: "中繼資料", Crop: "裁切", Flatten: "扁平化", Header: "頁首", Footer: "頁尾", Sign: "簽名", Unlock: "解鎖", Protect: "保護", Compare: "比較", Redact: "遮蔽", OCR: "OCR", Sanitize: "清理", Verify: "驗證", Color: "色彩", Editor: "編輯器", Palette: "調色盤", Swapper: "替換器", Optimizer: "最佳化器", React: "React", Base64: "Base64", Favicon: "網站圖示", Pattern: "圖案", Maker: "產生器", QR: "QR", Code: "碼", Image: "圖片", Resize: "調整尺寸", Background: "背景", Remove: "移除", EXIF: "EXIF", Icon: "圖示", Resource: "資源", Pack: "包" },
  es: { Merge: "Unir", Split: "Dividir", Rotate: "Girar", Reorder: "Reordenar", Pages: "páginas", Extract: "Extraer", Delete: "Eliminar", Reverse: "Invertir", Duplicate: "Duplicar", to: "a", Text: "texto", Word: "Word", Excel: "Excel", PowerPoint: "PowerPoint", Compress: "Comprimir", Add: "Añadir", Watermark: "marca de agua", Page: "página", Numbers: "números", Edit: "Editar", Metadata: "metadatos", Crop: "Recortar", Flatten: "Aplanar", Header: "encabezado", Footer: "pie", Sign: "Firmar", Unlock: "Desbloquear", Protect: "Proteger", Compare: "Comparar", Redact: "Redactar", OCR: "OCR", Sanitize: "Limpiar", Verify: "Verificar", Color: "color", Editor: "editor", Palette: "paleta", Swapper: "intercambiador", Optimizer: "optimizador", React: "React", Base64: "Base64", Favicon: "favicon", Pattern: "patrón", Maker: "creador", QR: "QR", Code: "código", Image: "imagen", Resize: "Cambiar tamaño", Background: "fondo", Remove: "Quitar", EXIF: "EXIF", Icon: "icono", Resource: "recursos", Pack: "paquete" },
  "pt-BR": { Merge: "Mesclar", Split: "Dividir", Rotate: "Girar", Reorder: "Reordenar", Pages: "páginas", Extract: "Extrair", Delete: "Excluir", Reverse: "Inverter", Duplicate: "Duplicar", to: "para", Text: "texto", Word: "Word", Excel: "Excel", PowerPoint: "PowerPoint", Compress: "Comprimir", Add: "Adicionar", Watermark: "marca d’água", Page: "página", Numbers: "números", Edit: "Editar", Metadata: "metadados", Crop: "Recortar", Flatten: "Achatar", Header: "cabeçalho", Footer: "rodapé", Sign: "Assinar", Unlock: "Desbloquear", Protect: "Proteger", Compare: "Comparar", Redact: "Redigir", OCR: "OCR", Sanitize: "Limpar", Verify: "Verificar", Color: "cor", Editor: "editor", Palette: "paleta", Swapper: "trocador", Optimizer: "otimizador", React: "React", Base64: "Base64", Favicon: "favicon", Pattern: "padrão", Maker: "criador", QR: "QR", Code: "código", Image: "imagem", Resize: "Redimensionar", Background: "fundo", Remove: "Remover", EXIF: "EXIF", Icon: "ícone", Resource: "recursos", Pack: "pacote" },
  de: { Merge: "Zusammenführen", Split: "Teilen", Rotate: "Drehen", Reorder: "Ordnen", Pages: "Seiten", Extract: "Extrahieren", Delete: "Löschen", Reverse: "Umkehren", Duplicate: "Duplizieren", to: "zu", Text: "Text", Word: "Word", Excel: "Excel", PowerPoint: "PowerPoint", Compress: "Komprimieren", Add: "Hinzufügen", Watermark: "Wasserzeichen", Page: "Seite", Numbers: "Nummern", Edit: "Bearbeiten", Metadata: "Metadaten", Crop: "Zuschneiden", Flatten: "Reduzieren", Header: "Kopfzeile", Footer: "Fußzeile", Sign: "Signieren", Unlock: "Entsperren", Protect: "Schützen", Compare: "Vergleichen", Redact: "Schwärzen", OCR: "OCR", Sanitize: "Bereinigen", Verify: "Prüfen", Color: "Farbe", Editor: "Editor", Palette: "Palette", Swapper: "Tauscher", Optimizer: "Optimierer", React: "React", Base64: "Base64", Favicon: "Favicon", Pattern: "Muster", Maker: "Generator", QR: "QR", Code: "Code", Image: "Bild", Resize: "Bildgröße ändern", Background: "Hintergrund", Remove: "Entfernen", EXIF: "EXIF", Icon: "Icon", Resource: "Ressourcen", Pack: "Paket" },
  fr: { Merge: "Fusionner", Split: "Scinder", Rotate: "Pivoter", Reorder: "Réordonner", Pages: "pages", Extract: "Extraire", Delete: "Supprimer", Reverse: "Inverser", Duplicate: "Dupliquer", to: "vers", Text: "texte", Word: "Word", Excel: "Excel", PowerPoint: "PowerPoint", Compress: "Compresser", Add: "Ajouter", Watermark: "filigrane", Page: "page", Numbers: "numéros", Edit: "Modifier", Metadata: "métadonnées", Crop: "Recadrer", Flatten: "Aplatir", Header: "en-tête", Footer: "pied de page", Sign: "Signer", Unlock: "Déverrouiller", Protect: "Protéger", Compare: "Comparer", Redact: "Caviarder", OCR: "OCR", Sanitize: "Nettoyer", Verify: "Vérifier", Color: "couleur", Editor: "éditeur", Palette: "palette", Swapper: "remplaceur", Optimizer: "optimiseur", React: "React", Base64: "Base64", Favicon: "favicon", Pattern: "motif", Maker: "créateur", QR: "QR", Code: "code", Image: "image", Resize: "Redimensionner", Background: "arrière-plan", Remove: "Supprimer", EXIF: "EXIF", Icon: "icône", Resource: "ressources", Pack: "paquet" },
  ja: { Merge: "結合", Split: "分割", Rotate: "回転", Reorder: "並べ替え", Pages: "ページ", Extract: "抽出", Delete: "削除", Reverse: "逆順", Duplicate: "複製", to: "から", Text: "テキスト", Word: "Word", Excel: "Excel", PowerPoint: "PowerPoint", Compress: "圧縮", Add: "追加", Watermark: "透かし", Page: "ページ", Numbers: "番号", Edit: "編集", Metadata: "メタデータ", Crop: "クロップ", Flatten: "フラット化", Header: "ヘッダー", Footer: "フッター", Sign: "署名", Unlock: "ロック解除", Protect: "保護", Compare: "比較", Redact: "墨消し", OCR: "OCR", Sanitize: "サニタイズ", Verify: "検証", Color: "カラー", Editor: "エディター", Palette: "パレット", Swapper: "置換", Optimizer: "最適化", React: "React", Base64: "Base64", Favicon: "ファビコン", Pattern: "パターン", Maker: "メーカー", QR: "QR", Code: "コード", Image: "画像", Resize: "サイズ変更", Background: "背景", Remove: "削除", EXIF: "EXIF", Icon: "アイコン", Resource: "リソース", Pack: "パック" },
};

const localizedNamePhrases: Partial<Record<Locale, Record<string, string>>> = {
  "zh-CN": { "Header & Footer": "页眉与页脚", "Add Watermark": "添加水印", "Page Numbers": "页码", "Edit Metadata": "编辑元数据", "Icon Resource Pack": "图标资源包", "Image Compressor": "图片压缩器", "Image Background": "图片背景", "Remove EXIF": "移除 EXIF", "SVG Color Editor": "SVG 颜色编辑器", "SVG Palette Swapper": "SVG 调色板替换器", "SVG Pattern Maker": "SVG 图案生成器", "SVG QR Code": "SVG 二维码" },
  "zh-TW": { "Header & Footer": "頁首與頁尾", "Add Watermark": "新增浮水印", "Page Numbers": "頁碼", "Edit Metadata": "編輯中繼資料", "Icon Resource Pack": "圖示資源包", "Image Compressor": "圖片壓縮器", "Image Background": "圖片背景", "Remove EXIF": "移除 EXIF", "SVG Color Editor": "SVG 色彩編輯器", "SVG Palette Swapper": "SVG 調色盤替換器", "SVG Pattern Maker": "SVG 圖案產生器", "SVG QR Code": "SVG QR 碼" },
  es: { "Header & Footer": "Encabezado y pie", "Add Watermark": "Añadir marca de agua", "Page Numbers": "Números de página", "Edit Metadata": "Editar metadatos", "Icon Resource Pack": "Paquete de recursos de iconos", "Image Compressor": "Compresor de imágenes", "Image Background": "Fondo de imagen", "Remove EXIF": "Quitar EXIF", "SVG Color Editor": "Editor de color SVG", "SVG Palette Swapper": "Intercambiador de paleta SVG", "SVG Pattern Maker": "Creador de patrones SVG", "SVG QR Code": "Código QR SVG" },
  "pt-BR": { "Header & Footer": "Cabeçalho e rodapé", "Add Watermark": "Adicionar marca d’água", "Page Numbers": "Números de página", "Edit Metadata": "Editar metadados", "Icon Resource Pack": "Pacote de recursos de ícones", "Image Compressor": "Compressor de imagens", "Image Background": "Fundo da imagem", "Remove EXIF": "Remover EXIF", "SVG Color Editor": "Editor de cores SVG", "SVG Palette Swapper": "Trocador de paleta SVG", "SVG Pattern Maker": "Criador de padrões SVG", "SVG QR Code": "Código QR SVG" },
  de: { "Header & Footer": "Kopf- und Fußzeile", "Add Watermark": "Wasserzeichen hinzufügen", "Page Numbers": "Seitenzahlen", "Edit Metadata": "Metadaten bearbeiten", "Icon Resource Pack": "Icon-Ressourcenpaket", "Image Compressor": "Bildkompressor", "Image Background": "Bildhintergrund", "Remove EXIF": "EXIF entfernen", "SVG Color Editor": "SVG-Farbeditor", "SVG Palette Swapper": "SVG-Palettentausch", "SVG Pattern Maker": "SVG-Mustergenerator", "SVG QR Code": "SVG-QR-Code" },
  fr: { "Header & Footer": "En-tête et pied de page", "Add Watermark": "Ajouter un filigrane", "Page Numbers": "Numéros de page", "Edit Metadata": "Modifier les métadonnées", "Icon Resource Pack": "Pack de ressources d’icônes", "Image Compressor": "Compresseur d’images", "Image Background": "Arrière-plan de l’image", "Remove EXIF": "Supprimer EXIF", "SVG Color Editor": "Éditeur de couleurs SVG", "SVG Palette Swapper": "Remplaceur de palette SVG", "SVG Pattern Maker": "Créateur de motifs SVG", "SVG QR Code": "Code QR SVG" },
  ja: { "Header & Footer": "ヘッダーとフッター", "Add Watermark": "透かしを追加", "Page Numbers": "ページ番号", "Edit Metadata": "メタデータを編集", "Icon Resource Pack": "アイコン素材パック", "Image Compressor": "画像圧縮", "Image Background": "画像の背景", "Remove EXIF": "EXIF を削除", "SVG Color Editor": "SVG カラーエディター", "SVG Palette Swapper": "SVG パレット置換", "SVG Pattern Maker": "SVG パターンメーカー", "SVG QR Code": "SVG QR コード" },
};

function replaceNameWords(name: string, locale: Locale): string { let result = name; for (const [from, to] of Object.entries(localizedNamePhrases[locale] ?? {}).sort(([a], [b]) => b.length - a.length)) result = result.replaceAll(from, to); const words = localizedNameWords[locale] ?? {}; for (const [from, to] of Object.entries(words).sort(([a], [b]) => b.length - a.length)) result = result.replace(new RegExp(`\\b${from.replace(/[.*+?^${}()|[\\]\\]/g, "\\$&")}\\b`, "g"), to); return result; }
export function getLocalizedToolName(locale: Locale, tool: Tool): string { return isExpandedLocale(locale) ? expandedToolName(locale, tool.name) : locale === "ko" || locale === "it" ? additionalToolName(locale, tool.name) : locale === "en" ? tool.name : replaceNameWords(tool.name, locale); }
export function getLocalizedToolDescription(locale: Locale, tool: Tool): string { if (locale === "en") return tool.shortDescription; const name = getLocalizedToolName(locale, tool); const input = tool.inputFormats.join("、"); const output = tool.outputFormats.join("、"); const templates: Record<Locale, string> = { ...expandedMap(c => formatLocale(c.dynamic.description, { name, input, output })), ko: `${name}: ${input} 입력을 ${output} 형식으로 처리합니다. 옵션과 지원 범위를 확인하세요.`, it: `${name}: elabora ${input} e genera ${output}. Controlla opzioni e limiti prima di scaricare.`, en: `${name}: process ${input} and create ${output}. Review the task options and support limits before downloading.`, "zh-CN": `${name}：处理${input}并生成${output}。下载前请查看任务选项、限制和隐私边界。`, "zh-TW": `${name}：處理${input}並產生${output}。下載前請查看任務選項、限制與隱私邊界。`, es: `${name}: procesa ${input} y crea ${output}. Revisa las opciones, límites y privacidad antes de descargar.`, "pt-BR": `${name}: processe ${input} e crie ${output}. Confira opções, limites e privacidade antes de baixar.`, de: `${name}: ${input} verarbeiten und ${output} erstellen. Optionen, Grenzen und Datenschutz vor dem Download prüfen.`, fr: `${name} : traiter ${input} et créer ${output}. Vérifiez les options, limites et la confidentialité avant le téléchargement.`, ja: `${name}：${input}を処理して${output}を作成します。ダウンロード前にオプション、制限、プライバシーを確認してください。` }; return templates[locale]; }

const optionLabels: Record<Locale, Record<string, string>> = {
  ...expandedMap(c => c.options),
  ko: additionalToolCopy.ko.options, it: additionalToolCopy.it.options,

  en: {},
  "zh-CN": { "Page range": "页面范围", "Pages to duplicate": "要复制的页面", Repeats: "重复次数", "Insert position": "插入位置", Quality: "质量", Width: "宽度", Height: "高度", "Resolution (DPI)": "分辨率（DPI）", "Create one long image": "生成一张长图", "Paper": "纸张", "Margin (pt)": "边距（点）", Fit: "适应方式", "PDF password": "PDF 密码", "New PDF password": "新 PDF 密码", "OCR language(s)": "OCR 语言", "Terms to remove (comma separated)": "要移除的词语（用逗号分隔）", "Watermark text": "水印文字", "Text size": "文字大小", Opacity: "不透明度", "Start number": "起始编号", "Page number format ({page} supported)": "页码格式（支持 {page}）", Position: "位置", Title: "标题", Author: "作者", Subject: "主题", Keywords: "关键词", "Crop inset (pt)": "裁切内缩（点）", "Page width (pt)": "页面宽度（点）", "Page height (pt)": "页面高度（点）", "Header ({page} supported)": "页眉（支持 {page}）", "Footer ({page} supported)": "页脚（支持 {page}）" },
  "zh-TW": { "Page range": "頁面範圍", "Pages to duplicate": "要複製的頁面", Repeats: "重複次數", "Insert position": "插入位置", Quality: "品質", Width: "寬度", Height: "高度", "Resolution (DPI)": "解析度（DPI）", "Create one long image": "建立一張長圖", Paper: "紙張", "Margin (pt)": "邊界（點）", Fit: "適應方式", "PDF password": "PDF 密碼", "New PDF password": "新 PDF 密碼", "OCR language(s)": "OCR 語言", "Terms to remove (comma separated)": "要移除的詞語（以逗號分隔）", "Watermark text": "浮水印文字", "Text size": "文字大小", Opacity: "不透明度", "Start number": "起始編號", "Page number format ({page} supported)": "頁碼格式（支援 {page}）", Position: "位置", Title: "標題", Author: "作者", Subject: "主旨", Keywords: "關鍵字", "Crop inset (pt)": "裁切內縮（點）", "Page width (pt)": "頁面寬度（點）", "Page height (pt)": "頁面高度（點）", "Header ({page} supported)": "頁首（支援 {page}）", "Footer ({page} supported)": "頁尾（支援 {page}）" },
  es: { "Page range": "Rango de páginas", "Pages to duplicate": "Páginas a duplicar", Repeats: "Repeticiones", "Insert position": "Posición de inserción", Quality: "Calidad", Width: "Ancho", Height: "Alto", "Resolution (DPI)": "Resolución (DPI)", "Create one long image": "Crear una imagen larga", Paper: "Papel", "Margin (pt)": "Margen (pt)", Fit: "Ajuste", "PDF password": "Contraseña del PDF", "New PDF password": "Nueva contraseña del PDF", "OCR language(s)": "Idioma(s) de OCR", "Terms to remove (comma separated)": "Términos a quitar (separados por comas)", "Watermark text": "Texto de marca de agua", "Text size": "Tamaño del texto", Opacity: "Opacidad", "Start number": "Número inicial", "Page number format ({page} supported)": "Formato de número de página (admite {page})", Position: "Posición", Title: "Título", Author: "Autor", Subject: "Asunto", Keywords: "Palabras clave", "Crop inset (pt)": "Margen de recorte (pt)", "Page width (pt)": "Ancho de página (pt)", "Page height (pt)": "Alto de página (pt)", "Header ({page} supported)": "Encabezado (admite {page})", "Footer ({page} supported)": "Pie (admite {page})" },
  "pt-BR": { "Page range": "Intervalo de páginas", "Pages to duplicate": "Páginas para duplicar", Repeats: "Repetições", "Insert position": "Posição de inserção", Quality: "Qualidade", Width: "Largura", Height: "Altura", "Resolution (DPI)": "Resolução (DPI)", "Create one long image": "Criar uma imagem longa", Paper: "Papel", "Margin (pt)": "Margem (pt)", Fit: "Ajuste", "PDF password": "Senha do PDF", "New PDF password": "Nova senha do PDF", "OCR language(s)": "Idioma(s) do OCR", "Terms to remove (comma separated)": "Termos para remover (separados por vírgula)", "Watermark text": "Texto da marca d’água", "Text size": "Tamanho do texto", Opacity: "Opacidade", "Start number": "Número inicial", "Page number format ({page} supported)": "Formato do número da página (aceita {page})", Position: "Posição", Title: "Título", Author: "Autor", Subject: "Assunto", Keywords: "Palavras-chave", "Crop inset (pt)": "Recuo do corte (pt)", "Page width (pt)": "Largura da página (pt)", "Page height (pt)": "Altura da página (pt)", "Header ({page} supported)": "Cabeçalho (aceita {page})", "Footer ({page} supported)": "Rodapé (aceita {page})" },
  de: { "Page range": "Seitenbereich", "Pages to duplicate": "Zu duplizierende Seiten", Repeats: "Wiederholungen", "Insert position": "Einfügeposition", Quality: "Qualität", Width: "Breite", Height: "Höhe", "Resolution (DPI)": "Auflösung (DPI)", "Create one long image": "Ein langes Bild erstellen", Paper: "Papier", "Margin (pt)": "Rand (pt)", Fit: "Anpassung", "PDF password": "PDF-Passwort", "New PDF password": "Neues PDF-Passwort", "OCR language(s)": "OCR-Sprache(n)", "Terms to remove (comma separated)": "Zu entfernende Begriffe (kommagetrennt)", "Watermark text": "Wasserzeichentext", "Text size": "Textgröße", Opacity: "Deckkraft", "Start number": "Startnummer", "Page number format ({page} supported)": "Seitenzahlenformat ({page} unterstützt)", Position: "Position", Title: "Titel", Author: "Autor", Subject: "Betreff", Keywords: "Schlüsselwörter", "Crop inset (pt)": "Zuschneiderand (pt)", "Page width (pt)": "Seitenbreite (pt)", "Page height (pt)": "Seitenhöhe (pt)", "Header ({page} supported)": "Kopfzeile ({page} unterstützt)", "Footer ({page} supported)": "Fußzeile ({page} unterstützt)" },
  fr: { "Page range": "Plage de pages", "Pages to duplicate": "Pages à dupliquer", Repeats: "Répétitions", "Insert position": "Position d’insertion", Quality: "Qualité", Width: "Largeur", Height: "Hauteur", "Resolution (DPI)": "Résolution (DPI)", "Create one long image": "Créer une image longue", Paper: "Papier", "Margin (pt)": "Marge (pt)", Fit: "Ajustement", "PDF password": "Mot de passe PDF", "New PDF password": "Nouveau mot de passe PDF", "OCR language(s)": "Langue(s) OCR", "Terms to remove (comma separated)": "Termes à supprimer (séparés par des virgules)", "Watermark text": "Texte du filigrane", "Text size": "Taille du texte", Opacity: "Opacité", "Start number": "Numéro de départ", "Page number format ({page} supported)": "Format du numéro de page ({page} accepté)", Position: "Position", Title: "Titre", Author: "Auteur", Subject: "Objet", Keywords: "Mots-clés", "Crop inset (pt)": "Marge de recadrage (pt)", "Page width (pt)": "Largeur de page (pt)", "Page height (pt)": "Hauteur de page (pt)", "Header ({page} supported)": "En-tête ({page} accepté)", "Footer ({page} supported)": "Pied de page ({page} accepté)" },
  ja: { "Page range": "ページ範囲", "Pages to duplicate": "複製するページ", Repeats: "繰り返し", "Insert position": "挿入位置", Quality: "品質", Width: "幅", Height: "高さ", "Resolution (DPI)": "解像度（DPI）", "Create one long image": "1枚の長い画像を作成", Paper: "用紙", "Margin (pt)": "余白（pt）", Fit: "配置", "PDF password": "PDF パスワード", "New PDF password": "新しい PDF パスワード", "OCR language(s)": "OCR 言語", "Terms to remove (comma separated)": "削除する語句（カンマ区切り）", "Watermark text": "透かし文字列", "Text size": "文字サイズ", Opacity: "不透明度", "Start number": "開始番号", "Page number format ({page} supported)": "ページ番号形式（{page} 対応）", Position: "位置", Title: "タイトル", Author: "作成者", Subject: "件名", Keywords: "キーワード", "Crop inset (pt)": "クロップ内側（pt）", "Page width (pt)": "ページ幅（pt）", "Page height (pt)": "ページ高さ（pt）", "Header ({page} supported)": "ヘッダー（{page} 対応）", "Footer ({page} supported)": "フッター（{page} 対応）" },
};
const additionalOptionLabels: Record<Locale, Record<string, string>> = {
  ...expandedMap(() => ({})),
  ko: {}, it: {},

  en: { Orientation: "Orientation", "Background color": "Background color", "Replacement color": "Replacement color", Palette: "Palette", Scale: "Scale", Rotation: "Rotation", Flip: "Flip", Padding: "Padding", "Signature text": "Signature text", "Frame (1 = first)": "Frame (1 = first)", "Visual page diff": "Visual page diff", "Compression mode": "Compression mode", "QR content": "QR content", "Error correction": "Error correction", "Page preset": "Page preset" },
  "zh-CN": { Orientation: "方向", "Background color": "背景颜色", "Replacement color": "替换颜色", Palette: "调色板", Scale: "倍数", Rotation: "旋转", Flip: "翻转", Padding: "留白", "Signature text": "签名文字", "Frame (1 = first)": "帧（1 = 首帧）", "Visual page diff": "页面视觉差异", "Compression mode": "压缩模式", "QR content": "二维码内容", "Error correction": "纠错级别", "Page preset": "页面预设" },
  "zh-TW": { Orientation: "方向", "Background color": "背景色", "Replacement color": "替換色彩", Palette: "調色盤", Scale: "倍數", Rotation: "旋轉", Flip: "翻轉", Padding: "留白", "Signature text": "簽名文字", "Frame (1 = first)": "影格（1 = 第一格）", "Visual page diff": "頁面視覺差異", "Compression mode": "壓縮模式", "QR content": "QR 內容", "Error correction": "錯誤修正", "Page preset": "頁面預設" },
  es: { Orientation: "Orientación", "Background color": "Color de fondo", "Replacement color": "Color de reemplazo", Palette: "Paleta", Scale: "Escala", Rotation: "Rotación", Flip: "Voltear", Padding: "Relleno", "Signature text": "Texto de firma", "Frame (1 = first)": "Fotograma (1 = primero)", "Visual page diff": "Diferencia visual de páginas", "Compression mode": "Modo de compresión", "QR content": "Contenido QR", "Error correction": "Corrección de errores", "Page preset": "Preajuste de página" },
  "pt-BR": { Orientation: "Orientação", "Background color": "Cor de fundo", "Replacement color": "Cor de substituição", Palette: "Paleta", Scale: "Escala", Rotation: "Rotação", Flip: "Virar", Padding: "Margem interna", "Signature text": "Texto da assinatura", "Frame (1 = first)": "Quadro (1 = primeiro)", "Visual page diff": "Diferença visual das páginas", "Compression mode": "Modo de compressão", "QR content": "Conteúdo do QR", "Error correction": "Correção de erros", "Page preset": "Predefinição de página" },
  de: { Orientation: "Ausrichtung", "Background color": "Hintergrundfarbe", "Replacement color": "Ersatzfarbe", Palette: "Palette", Scale: "Skalierung", Rotation: "Drehung", Flip: "Spiegeln", Padding: "Innenabstand", "Signature text": "Signaturtext", "Frame (1 = first)": "Frame (1 = erster)", "Visual page diff": "Visueller Seitenvergleich", "Compression mode": "Komprimierungsmodus", "QR content": "QR-Inhalt", "Error correction": "Fehlerkorrektur", "Page preset": "Seitenvorgabe" },
  fr: { Orientation: "Orientation", "Background color": "Couleur d’arrière-plan", "Replacement color": "Couleur de remplacement", Palette: "Palette", Scale: "Échelle", Rotation: "Rotation", Flip: "Retourner", Padding: "Marge interne", "Signature text": "Texte de signature", "Frame (1 = first)": "Image (1 = première)", "Visual page diff": "Différence visuelle des pages", "Compression mode": "Mode de compression", "QR content": "Contenu QR", "Error correction": "Correction d’erreur", "Page preset": "Préréglage de page" },
  ja: { Orientation: "向き", "Background color": "背景色", "Replacement color": "置換色", Palette: "パレット", Scale: "倍率", Rotation: "回転", Flip: "反転", Padding: "余白", "Signature text": "署名テキスト", "Frame (1 = first)": "フレーム（1 = 最初）", "Visual page diff": "ページの視覚差分", "Compression mode": "圧縮モード", "QR content": "QR 内容", "Error correction": "誤り訂正", "Page preset": "ページプリセット" },
};
export function getLocalizedOptionLabel(locale: Locale, label: string): string { return (label === "Page order (for example 2,1,3)" ? getWorkspaceCopy(locale).order : undefined) ?? optionLabels[locale][label] ?? additionalOptionLabels[locale][label] ?? label; }
export function getLocalizedToolLimits(locale: Locale, tool: Tool): string { const files = tool.limits.maxFiles ?? 1; const mb = tool.limits.maxMb ?? 8; const pages = tool.limits.maxPages ? `, ${tool.limits.maxPages} pages` : ""; const templates: Record<Locale, string> = { ...expandedMap(c => formatLocale(c.dynamic.limits, { files, mb, pages: tool.limits.maxPages ? formatLocale(c.dynamic.pages, { count: tool.limits.maxPages }) : "" })), ko: `최대 ${files}개 파일, 입력당 ${mb} MB${tool.limits.maxPages ? ", " + tool.limits.maxPages + "페이지" : ""}. 다운로드 전에 결과를 확인하세요.`, it: `Massimo ${files} file, ${mb} MB per file${tool.limits.maxPages ? " e " + tool.limits.maxPages + " pagine" : ""}. Verifica il risultato prima del download.`, en: `Up to ${files} file${files === 1 ? "" : "s"}, ${mb} MB per input${pages}. ${tool.qualityNotes}`, "zh-CN": `最多 ${files} 个文件，每个输入不超过 ${mb} MB${tool.limits.maxPages ? `，最多 ${tool.limits.maxPages} 页` : ""}。输出会在下载前检查。`, "zh-TW": `最多 ${files} 個檔案，每個輸入不超過 ${mb} MB${tool.limits.maxPages ? `，最多 ${tool.limits.maxPages} 頁` : ""}。輸出會在下載前檢查。`, es: `Hasta ${files} archivo${files === 1 ? "" : "s"}, ${mb} MB por entrada${tool.limits.maxPages ? ` y ${tool.limits.maxPages} páginas` : ""}. La salida se comprueba antes de descargar.`, "pt-BR": `Até ${files} arquivo${files === 1 ? "" : "s"}, ${mb} MB por entrada${tool.limits.maxPages ? ` e ${tool.limits.maxPages} páginas` : ""}. A saída é verificada antes do download.`, de: `Bis zu ${files} Datei${files === 1 ? "" : "en"}, ${mb} MB pro Eingabe${tool.limits.maxPages ? ` und ${tool.limits.maxPages} Seiten` : ""}. Die Ausgabe wird vor dem Download geprüft.`, fr: `Jusqu’à ${files} fichier${files === 1 ? "" : "s"}, ${mb} Mo par entrée${tool.limits.maxPages ? ` et ${tool.limits.maxPages} pages` : ""}. La sortie est vérifiée avant le téléchargement.`, ja: `最大 ${files} ファイル、入力 ${mb} MB${tool.limits.maxPages ? `、${tool.limits.maxPages} ページ` : ""}。ダウンロード前に出力を確認します。` }; return templates[locale] + pixelLimitText(locale, tool.limits.maxPixels); }

export type ToolFaqItem = { question: string; answer: string };

const faqText: Record<Locale, { formats: string; mode: string; options: string; noOptions: string; local: string; server: string }> = {
  ...packMap(c => c.faq),
  ko: additionalLocales.ko.faq, it: additionalLocales.it.faq,

  en: { formats: "Which files can I use?", mode: "Does this task upload my file?", options: "Which options are available?", noOptions: "This task has no extra options; add a supported file and process it.", local: "It runs in this browser. Your file is not uploaded automatically.", server: "It uses server-side processing. The workspace asks for explicit upload consent before sending the file." },
  "zh-CN": { formats: "支持哪些文件？", mode: "这个任务会上传我的文件吗？", options: "有哪些可用选项？", noOptions: "此任务没有额外选项；添加支持的文件后即可处理。", local: "此任务在浏览器中运行，不会自动上传文件。", server: "此任务在服务端处理，工作台会在发送文件前明确请求上传同意。" },
  "zh-TW": { formats: "支援哪些檔案？", mode: "這個任務會上傳我的檔案嗎？", options: "有哪些可用選項？", noOptions: "此任務沒有額外選項；加入支援的檔案後即可處理。", local: "此任務在瀏覽器中執行，不會自動上傳檔案。", server: "此任務在伺服器端處理，工作台會在傳送檔案前明確請求上傳同意。" },
  es: { formats: "¿Qué archivos puedo usar?", mode: "¿Esta tarea sube mi archivo?", options: "¿Qué opciones hay?", noOptions: "Esta tarea no tiene opciones adicionales: añade un archivo compatible y procésalo.", local: "Se ejecuta en este navegador. El archivo no se sube automáticamente.", server: "Se procesa en el servidor. El espacio de trabajo pide permiso explícito antes de enviar el archivo." },
  "pt-BR": { formats: "Quais arquivos posso usar?", mode: "Esta tarefa envia meu arquivo?", options: "Quais opções estão disponíveis?", noOptions: "Esta tarefa não tem opções extras; adicione um arquivo compatível e processe-o.", local: "Ela roda neste navegador. Seu arquivo não é enviado automaticamente.", server: "Ela é processada no servidor. O espaço de trabalho pede consentimento explícito antes do envio." },
  de: { formats: "Welche Dateien kann ich verwenden?", mode: "Wird meine Datei hochgeladen?", options: "Welche Optionen gibt es?", noOptions: "Diese Aufgabe hat keine zusätzlichen Optionen. Eine unterstützte Datei hinzufügen und verarbeiten.", local: "Sie läuft in diesem Browser. Die Datei wird nicht automatisch hochgeladen.", server: "Sie wird auf dem Server verarbeitet. Vor dem Senden wird ausdrücklich um Zustimmung gebeten." },
  fr: { formats: "Quels fichiers puis-je utiliser ?", mode: "Cette tâche envoie-t-elle mon fichier ?", options: "Quelles options sont disponibles ?", noOptions: "Cette tâche n’a pas d’option supplémentaire : ajoutez un fichier compatible puis lancez le traitement.", local: "Elle s’exécute dans ce navigateur. Le fichier n’est pas envoyé automatiquement.", server: "Elle est traitée sur le serveur. L’espace de travail demande votre accord avant l’envoi." },
  ja: { formats: "どのファイルを使えますか？", mode: "このタスクでファイルはアップロードされますか？", options: "どのオプションを使えますか？", noOptions: "追加オプションはありません。対応ファイルを追加して処理してください。", local: "このブラウザー内で処理します。ファイルは自動アップロードされません。", server: "サーバーで処理します。送信前にワークスペースで明示的な同意を求めます。" },
};

export function getToolFaq(locale: Locale, tool: Tool): ToolFaqItem[] {
  const text = faqText[locale];
  const name = getLocalizedToolName(locale, tool);
  const joiner = locale === "ja" || locale.startsWith("zh") ? "、" : ", ";
  const input = tool.inputFormats.join(joiner);
  const output = tool.outputFormats.join(joiner);
  const options = tool.optionSchema.map((option) => getLocalizedOptionLabel(locale, option.label)).join(joiner);
  const modeAnswer = tool.processingMode === "local" ? text.local : text.server;
  const formatsAnswer: Record<Locale, string> = {
    ...expandedMap(c => formatLocale(c.dynamic.formats, { name, input, output })),
  ko: `${name}: ${input} 입력으로 ${output} 결과를 생성합니다. 처리 전에 실제 형식을 확인합니다.`, it: `${name} accetta ${input} e genera ${output}. Il formato effettivo viene verificato prima di elaborare.`,

    en: `${name} accepts ${input} and creates ${output}. The actual file type is checked before processing.`,
    "zh-CN": `${name} 接受 ${input}，生成 ${output}。处理前会检查实际文件类型。`,
    "zh-TW": `${name} 接受 ${input}，產生 ${output}。處理前會檢查實際檔案類型。`,
    es: `${name} acepta ${input} y crea ${output}. El tipo real del archivo se comprueba antes de procesar.`,
    "pt-BR": `${name} aceita ${input} e cria ${output}. O tipo real do arquivo é verificado antes do processamento.`,
    de: `${name} akzeptiert ${input} und erstellt ${output}. Der tatsächliche Dateityp wird vor der Verarbeitung geprüft.`,
    fr: `${name} accepte ${input} et crée ${output}. Le type réel du fichier est vérifié avant le traitement.`,
    ja: `${name} は ${input} を受け付け、${output} を作成します。処理前に実際のファイル形式を確認します。`,
  };
  const optionsAnswer: Record<Locale, string> = {
    ...expandedMap(c => options ? formatLocale(c.dynamic.options, { options }) : c.faq.noOptions),
  ko: options ? "사용 가능한 옵션: " + options + "." : text.noOptions, it: options ? "Opzioni disponibili: " + options + "." : text.noOptions,

    en: options ? `Available controls include: ${options}.` : text.noOptions,
    "zh-CN": options ? `可用控制项包括：${options}。` : text.noOptions,
    "zh-TW": options ? `可用控制項包括：${options}。` : text.noOptions,
    es: options ? `Los controles disponibles incluyen: ${options}.` : text.noOptions,
    "pt-BR": options ? `Os controles disponíveis incluem: ${options}.` : text.noOptions,
    de: options ? `Verfügbare Einstellungen: ${options}.` : text.noOptions,
    fr: options ? `Les réglages disponibles comprennent : ${options}.` : text.noOptions,
    ja: options ? `利用できる設定は ${options} です。` : text.noOptions,
  };
  return [
    { question: text.formats, answer: formatsAnswer[locale] },
    { question: text.mode, answer: modeAnswer },
    // These defaults are persisted as editable content. Live limits belong in the
    // dedicated effective-config section, not a snapshot that becomes stale in FAQ.
    { question: text.options, answer: optionsAnswer[locale] },
  ];
}

export type HomeCopy = { trust: [string, string, string, string]; browseTitle: string; browseDescription: string; workflowItems: Array<[string, string, string]> };
const homeCopy: Record<Locale, HomeCopy> = {
  ...packMap(c => c.home),
  ko: additionalLocales.ko.home as HomeCopy, it: additionalLocales.it.home as HomeCopy,

  en: { trust: ["No account required", "Browser-first processing", "Clear format boundaries", "15 min server result TTL"], browseTitle: "Four ways in.", browseDescription: "Browse by the file you have, not by a complicated feature matrix.", workflowItems: [["01 / CHOOSE", "Pick a task", "Every page explains its input, output and actual boundary."], ["02 / ADD", "Keep it close", "Local work never leaves the browser unless you choose a server task."], ["03 / CHECK", "See the change", "File size, dimensions and format are shown after processing."], ["04 / MOVE ON", "Continue the thread", "Use a result in a related tool during the same browser session."]] },
  "zh-CN": { trust: ["无需账号", "浏览器优先处理", "清晰的格式边界", "服务端结果保留 15 分钟"], browseTitle: "四种入口", browseDescription: "按你手上的文件浏览工具，而不是面对复杂的功能矩阵。", workflowItems: [["01 / 选择", "挑选任务", "每个页面都会说明输入、输出和真实处理边界。"], ["02 / 添加", "让文件留在手边", "除非主动选择服务端任务，否则文件不会离开浏览器。"], ["03 / 检查", "看见变化", "处理后会显示文件大小、尺寸和格式。"], ["04 / 继续", "接着处理", "在同一浏览器会话中把结果交给相关工具。"]] },
  "zh-TW": { trust: ["不需帳號", "瀏覽器優先處理", "清楚的格式邊界", "伺服器結果保留 15 分鐘"], browseTitle: "四種入口", browseDescription: "依你手上的檔案瀏覽工具，而不是面對複雜的功能矩陣。", workflowItems: [["01 / 選擇", "挑選任務", "每個頁面都會說明輸入、輸出與實際處理邊界。"], ["02 / 加入", "讓檔案留在手邊", "除非主動選擇伺服器任務，否則檔案不會離開瀏覽器。"], ["03 / 檢查", "看見變化", "處理後會顯示檔案大小、尺寸與格式。"], ["04 / 繼續", "接著處理", "在同一瀏覽器工作階段中把結果交給相關工具。"]] },
  es: { trust: ["Sin cuenta", "Procesamiento en navegador", "Formatos claramente delimitados", "Resultados de servidor: 15 min"], browseTitle: "Cuatro formas de empezar", browseDescription: "Explora según el archivo que tienes, no según una matriz complicada.", workflowItems: [["01 / ELEGIR", "Escoge una tarea", "Cada página explica su entrada, salida y límite real."], ["02 / AÑADIR", "Mantenlo cerca", "El trabajo local no sale del navegador salvo que elijas servidor."], ["03 / COMPROBAR", "Mira el cambio", "Después se muestran tamaño, dimensiones y formato."], ["04 / CONTINUAR", "Sigue el hilo", "Usa el resultado en una herramienta relacionada en la misma sesión."]] },
  "pt-BR": { trust: ["Sem conta", "Processamento no navegador", "Limites de formato claros", "Resultado no servidor: 15 min"], browseTitle: "Quatro formas de começar", browseDescription: "Navegue pelo arquivo que você tem, não por uma matriz complicada.", workflowItems: [["01 / ESCOLHER", "Escolha uma tarefa", "Cada página explica entrada, saída e limite real."], ["02 / ADICIONAR", "Mantenha por perto", "O trabalho local não sai do navegador sem sua escolha."], ["03 / CONFERIR", "Veja a mudança", "Tamanho, dimensões e formato aparecem após o processamento."], ["04 / CONTINUAR", "Siga o fluxo", "Use o resultado em uma ferramenta relacionada na mesma sessão."]] },
  de: { trust: ["Kein Konto nötig", "Browser zuerst", "Klare Formatgrenzen", "Serverergebnis: 15 Min."], browseTitle: "Vier Wege hinein", browseDescription: "Nach der vorhandenen Datei suchen, nicht nach einer komplizierten Funktionsmatrix.", workflowItems: [["01 / WÄHLEN", "Aufgabe wählen", "Jede Seite erklärt Eingabe, Ausgabe und echte Grenze."], ["02 / HINZUFÜGEN", "Datei nah halten", "Lokale Arbeit verlässt den Browser nur nach deiner Wahl."], ["03 / PRÜFEN", "Änderung sehen", "Nach der Verarbeitung werden Größe, Maße und Format gezeigt."], ["04 / WEITER", "Im Fluss bleiben", "Das Ergebnis in derselben Sitzung an ein verwandtes Werkzeug geben."]] },
  fr: { trust: ["Sans compte", "Traitement dans le navigateur", "Limites de format claires", "Résultat serveur : 15 min"], browseTitle: "Quatre portes d’entrée", browseDescription: "Parcourez les outils selon le fichier que vous avez, pas une matrice compliquée.", workflowItems: [["01 / CHOISIR", "Choisir une tâche", "Chaque page explique son entrée, sa sortie et sa limite réelle."], ["02 / AJOUTER", "Garder le fichier près de soi", "Le travail local ne quitte pas le navigateur sans votre choix."], ["03 / VÉRIFIER", "Voir le changement", "Taille, dimensions et format sont affichés après traitement."], ["04 / CONTINUER", "Poursuivre le fil", "Utilisez le résultat dans un outil associé pendant la même session."]] },
  ja: { trust: ["アカウント不要", "ブラウザー優先の処理", "明確な形式の境界", "サーバー結果は15分保持"], browseTitle: "4つの入口", browseDescription: "複雑な機能表ではなく、手元のファイルからツールを選べます。", workflowItems: [["01 / 選ぶ", "タスクを選択", "各ページで入力、出力、実際の処理範囲を説明します。"], ["02 / 追加", "手元に保つ", "サーバータスクを選ばない限り、ローカル作業はブラウザーから出ません。"], ["03 / 確認", "変化を見る", "処理後にサイズ、寸法、形式を表示します。"], ["04 / 続ける", "作業をつなぐ", "同じセッションで関連ツールに結果を渡せます。"]] },
};
export function getHomeCopy(locale: Locale): HomeCopy { return homeCopy[locale]; }

type FooterCopy = { tagline: string; guideOne: string; guideTwo: string; terms: string; contact: string; legal: string };
const footerCopy: Record<Locale, FooterCopy> = {
  ...packMap(c => c.footer),
  ko: additionalLocales.ko.footer, it: additionalLocales.it.footer,

  en: { tagline: "Quiet, capable tools for the files you already have.", guideOne: "Prepare images for the web", guideTwo: "PDF privacy basics", terms: "Terms", contact: "Contact", legal: "Built for local-first work. No advertising scripts." },
  "zh-CN": { tagline: "为你已有的文件提供安静、可靠的工具。", guideOne: "为网页准备图片", guideTwo: "PDF 隐私基础", terms: "条款", contact: "联系", legal: "为本地优先处理而建。不加载广告脚本。" },
  "zh-TW": { tagline: "為你已有的檔案提供安靜、可靠的工具。", guideOne: "為網頁準備圖片", guideTwo: "PDF 隱私基礎", terms: "條款", contact: "聯絡", legal: "為本機優先處理而建。不載入廣告腳本。" },
  es: { tagline: "Herramientas claras y capaces para tus archivos.", guideOne: "Preparar imágenes para la web", guideTwo: "Privacidad básica de los PDF", terms: "Condiciones", contact: "Contacto", legal: "Creado para el trabajo local. Sin scripts publicitarios." },
  "pt-BR": { tagline: "Ferramentas simples e capazes para os arquivos que você já tem.", guideOne: "Preparar imagens para a web", guideTwo: "Noções de privacidade em PDF", terms: "Termos", contact: "Contato", legal: "Feito para o trabalho local. Sem scripts de publicidade." },
  de: { tagline: "Ruhige, leistungsfähige Werkzeuge für deine vorhandenen Dateien.", guideOne: "Bilder für das Web vorbereiten", guideTwo: "PDF-Datenschutzgrundlagen", terms: "Bedingungen", contact: "Kontakt", legal: "Für lokale Verarbeitung gebaut. Keine Werbeskripte." },
  fr: { tagline: "Des outils simples et fiables pour les fichiers que vous avez déjà.", guideOne: "Préparer des images pour le web", guideTwo: "Bases de la confidentialité des PDF", terms: "Conditions", contact: "Contact", legal: "Conçu pour le traitement local. Aucun script publicitaire." },
  ja: { tagline: "手元のファイルのための、静かで確かなツール。", guideOne: "Web 用画像を準備する", guideTwo: "PDF のプライバシー基礎", terms: "利用規約", contact: "お問い合わせ", legal: "ローカル優先のために設計。広告スクリプトはありません。" },
};
export function getFooterCopy(locale: Locale): FooterCopy { return footerCopy[locale]; }
