import type { Locale } from "@hxsl/tool-registry";

type PageCopy = { range: string; order: string; repeats: string; position: string; limit: string; deleteAll: string; earlier: string; later: string };
export const pdfPageCopy: Record<Locale, PageCopy> = {
  en: { range: "Page ranges must stay between 1 and {n}. Use whole numbers, commas or a range such as 1-3.", order: "Reorder must contain every page number exactly once, from 1 to {n}.", repeats: "Repeats must be a whole number between 1 and 10.", position: "Insert position must be a whole number between 0 and {n}. Use 0 to insert at the beginning.", limit: "This PDF exceeds the {n}-page limit. Select fewer pages or reduce repeats.", deleteAll: "Deleting all pages would create an invalid empty PDF. Keep at least one page.", earlier: "Move page {n} earlier", later: "Move page {n} later" },
  "zh-CN": { range: "页面范围必须在 1 到 {n} 之间。请使用整数、逗号或 1-3 这样的范围。", order: "请填写 1 到 {n} 的完整页序，每个页码只能出现一次。", repeats: "重复次数必须是 1 到 10 之间的整数。", position: "插入位置必须是 0 到 {n} 之间的整数。0 表示插入到最前面。", limit: "此 PDF 超过 {n} 页的限制。请减少选择的页面或重复次数。", deleteAll: "不能删除全部页面，否则会产生无效的空 PDF。请至少保留一页。", earlier: "将第 {n} 页前移", later: "将第 {n} 页后移" },
  "zh-TW": { range: "頁面範圍必須在 1 到 {n} 之間。請使用整數、逗號或 1-3 這樣的範圍。", order: "請填寫 1 到 {n} 的完整頁序，每個頁碼只能出現一次。", repeats: "重複次數必須是 1 到 10 之間的整數。", position: "插入位置必須是 0 到 {n} 之間的整數。0 表示插入到最前面。", limit: "此 PDF 超過 {n} 頁的限制。請減少選取的頁面或重複次數。", deleteAll: "不能刪除全部頁面，否則會產生無效的空 PDF。請至少保留一頁。", earlier: "將第 {n} 頁前移", later: "將第 {n} 頁後移" },
  es: { range: "El rango debe estar entre 1 y {n}. Usa números enteros, comas o un rango como 1-3.", order: "Incluye cada número de página del 1 al {n} exactamente una vez.", repeats: "Las repeticiones deben ser un número entero entre 1 y 10.", position: "La posición debe ser un número entero entre 0 y {n}. Usa 0 para insertar al principio.", limit: "El PDF supera el límite de {n} páginas. Selecciona menos páginas o reduce las repeticiones.", deleteAll: "No se pueden eliminar todas las páginas: el PDF vacío no sería válido. Conserva al menos una.", earlier: "Mover la página {n} antes", later: "Mover la página {n} después" },
  "pt-BR": { range: "O intervalo deve ficar entre 1 e {n}. Use números inteiros, vírgulas ou um intervalo como 1-3.", order: "Inclua cada número de página de 1 a {n} exatamente uma vez.", repeats: "O número de repetições deve ser um inteiro entre 1 e 10.", position: "A posição deve ser um inteiro entre 0 e {n}. Use 0 para inserir no início.", limit: "O PDF excede o limite de {n} páginas. Selecione menos páginas ou reduza as repetições.", deleteAll: "Não é possível excluir todas as páginas: um PDF vazio seria inválido. Mantenha pelo menos uma.", earlier: "Mover a página {n} para antes", later: "Mover a página {n} para depois" },
  de: { range: "Der Seitenbereich muss zwischen 1 und {n} liegen. Verwende ganze Zahlen, Kommas oder einen Bereich wie 1-3.", order: "Gib jede Seitennummer von 1 bis {n} genau einmal an.", repeats: "Die Anzahl der Wiederholungen muss eine ganze Zahl zwischen 1 und 10 sein.", position: "Die Einfügeposition muss eine ganze Zahl zwischen 0 und {n} sein. Mit 0 wird am Anfang eingefügt.", limit: "Die PDF überschreitet die Grenze von {n} Seiten. Wähle weniger Seiten oder Wiederholungen.", deleteAll: "Alle Seiten zu löschen würde eine ungültige leere PDF erzeugen. Behalte mindestens eine Seite.", earlier: "Seite {n} nach vorne verschieben", later: "Seite {n} nach hinten verschieben" },
  fr: { range: "La plage doit être comprise entre 1 et {n}. Utilisez des entiers, des virgules ou une plage comme 1-3.", order: "Indiquez chaque numéro de page de 1 à {n} exactement une fois.", repeats: "Le nombre de répétitions doit être un entier compris entre 1 et 10.", position: "La position doit être un entier compris entre 0 et {n}. Utilisez 0 pour insérer au début.", limit: "Le PDF dépasse la limite de {n} pages. Sélectionnez moins de pages ou réduisez les répétitions.", deleteAll: "Supprimer toutes les pages créerait un PDF vide non valide. Conservez au moins une page.", earlier: "Déplacer la page {n} vers le début", later: "Déplacer la page {n} vers la fin" },
  ja: { range: "ページ範囲は 1～{n} で指定してください。整数、カンマ、または 1-3 のような範囲を使用できます。", order: "1～{n} の各ページ番号を一度ずつ指定してください。", repeats: "繰り返し回数は 1～10 の整数で指定してください。", position: "挿入位置は 0～{n} の整数で指定してください。0 は先頭への挿入です。", limit: "PDF が上限の {n} ページを超えています。選択ページ数または繰り返し回数を減らしてください。", deleteAll: "全ページを削除すると無効な空の PDF になります。少なくとも 1 ページを残してください。", earlier: "ページ {n} を前へ移動", later: "ページ {n} を後ろへ移動" },
  ko: { range: "페이지 범위는 1~{n}이어야 합니다. 정수, 쉼표 또는 1-3과 같은 범위를 사용하세요.", order: "1~{n}의 모든 페이지 번호를 한 번씩 입력하세요.", repeats: "반복 횟수는 1~10 사이의 정수여야 합니다.", position: "삽입 위치는 0~{n} 사이의 정수여야 합니다. 0은 맨 앞에 삽입합니다.", limit: "PDF가 최대 {n}페이지를 초과합니다. 선택한 페이지나 반복 횟수를 줄이세요.", deleteAll: "모든 페이지를 삭제하면 유효하지 않은 빈 PDF가 됩니다. 한 페이지 이상 남겨 두세요.", earlier: "{n}페이지를 앞으로 이동", later: "{n}페이지를 뒤로 이동" },
  it: { range: "L’intervallo deve essere compreso tra 1 e {n}. Usa numeri interi, virgole o un intervallo come 1-3.", order: "Inserisci ogni numero di pagina da 1 a {n} esattamente una volta.", repeats: "Le ripetizioni devono essere un numero intero tra 1 e 10.", position: "La posizione deve essere un numero intero tra 0 e {n}. Usa 0 per inserire all’inizio.", limit: "Il PDF supera il limite di {n} pagine. Seleziona meno pagine o riduci le ripetizioni.", deleteAll: "Eliminare tutte le pagine produrrebbe un PDF vuoto non valido. Mantieni almeno una pagina.", earlier: "Sposta la pagina {n} prima", later: "Sposta la pagina {n} dopo" },
  tr: { range: "Sayfa aralığı 1 ile {n} arasında olmalıdır. Tam sayılar, virgüller veya 1-3 gibi bir aralık kullanın.", order: "1 ile {n} arasındaki her sayfa numarasını tam bir kez girin.", repeats: "Tekrar sayısı 1 ile 10 arasında bir tam sayı olmalıdır.", position: "Ekleme konumu 0 ile {n} arasında bir tam sayı olmalıdır. Başa eklemek için 0 kullanın.", limit: "PDF, {n} sayfa sınırını aşıyor. Daha az sayfa seçin veya tekrar sayısını azaltın.", deleteAll: "Tüm sayfaların silinmesi geçersiz, boş bir PDF oluşturur. En az bir sayfayı koruyun.", earlier: "{n}. sayfayı öne taşı", later: "{n}. sayfayı arkaya taşı" },
  vi: { range: "Phạm vi trang phải từ 1 đến {n}. Dùng số nguyên, dấu phẩy hoặc phạm vi như 1-3.", order: "Nhập mỗi số trang từ 1 đến {n} đúng một lần.", repeats: "Số lần lặp phải là số nguyên từ 1 đến 10.", position: "Vị trí chèn phải là số nguyên từ 0 đến {n}. Dùng 0 để chèn vào đầu.", limit: "PDF vượt giới hạn {n} trang. Hãy chọn ít trang hơn hoặc giảm số lần lặp.", deleteAll: "Xóa tất cả các trang sẽ tạo PDF trống không hợp lệ. Hãy giữ lại ít nhất một trang.", earlier: "Di chuyển trang {n} về trước", later: "Di chuyển trang {n} về sau" },
  nl: { range: "Het paginabereik moet tussen 1 en {n} liggen. Gebruik gehele getallen, komma’s of een bereik zoals 1-3.", order: "Voer elk paginanummer van 1 tot en met {n} precies één keer in.", repeats: "Het aantal herhalingen moet een geheel getal tussen 1 en 10 zijn.", position: "De invoegpositie moet een geheel getal tussen 0 en {n} zijn. Gebruik 0 om vooraan in te voegen.", limit: "De PDF overschrijdt de limiet van {n} pagina’s. Kies minder pagina’s of herhalingen.", deleteAll: "Alle pagina’s verwijderen zou een ongeldige lege PDF opleveren. Behoud minstens één pagina.", earlier: "Pagina {n} naar voren verplaatsen", later: "Pagina {n} naar achteren verplaatsen" },
  pl: { range: "Zakres stron musi mieścić się między 1 a {n}. Użyj liczb całkowitych, przecinków lub zakresu, np. 1-3.", order: "Wpisz każdy numer strony od 1 do {n} dokładnie raz.", repeats: "Liczba powtórzeń musi być liczbą całkowitą od 1 do 10.", position: "Pozycja wstawienia musi być liczbą całkowitą od 0 do {n}. Wpisz 0, aby wstawić na początku.", limit: "PDF przekracza limit stron: {n}. Wybierz mniej stron lub zmniejsz liczbę powtórzeń.", deleteAll: "Usunięcie wszystkich stron utworzyłoby nieprawidłowy pusty PDF. Zachowaj co najmniej jedną stronę.", earlier: "Przesuń stronę {n} wcześniej", later: "Przesuń stronę {n} później" },
  th: { range: "ช่วงหน้าต้องอยู่ระหว่าง 1 ถึง {n} ใช้จำนวนเต็ม เครื่องหมายจุลภาค หรือช่วง เช่น 1-3", order: "กรอกหมายเลขหน้าตั้งแต่ 1 ถึง {n} ให้ครบ โดยแต่ละหมายเลขปรากฏเพียงครั้งเดียว", repeats: "จำนวนครั้งที่ทำซ้ำต้องเป็นจำนวนเต็มตั้งแต่ 1 ถึง 10", position: "ตำแหน่งแทรกต้องเป็นจำนวนเต็มตั้งแต่ 0 ถึง {n} ใช้ 0 เพื่อแทรกไว้ที่จุดเริ่มต้น", limit: "PDF เกินขีดจำกัด {n} หน้า โปรดเลือกหน้าน้อยลงหรือลดจำนวนครั้งที่ทำซ้ำ", deleteAll: "การลบทุกหน้าจะทำให้ PDF ว่างและไม่ถูกต้อง โปรดเก็บไว้อย่างน้อยหนึ่งหน้า", earlier: "ย้ายหน้า {n} ไปก่อนหน้า", later: "ย้ายหน้า {n} ไปถัดไป" },
};
export type PdfPageErrorCode = Exclude<keyof PageCopy, "earlier" | "later">;
export function pdfPageMessage(locale: Locale, key: keyof PageCopy, value = 0) { return pdfPageCopy[locale][key].replaceAll("{n}", new Intl.NumberFormat(locale).format(value)); }
export class PdfPageError extends Error {
  constructor(readonly code: PdfPageErrorCode, readonly value = 0) { super(pdfPageMessage("en", code, value)); }
}
