import { additionalToolCopy } from "../../../../lib/additional-tool-copy";
import { LOCALES } from "@hxsl/tool-registry";
import type { Metadata } from "next";
import { notFound } from "next/navigation";
import Link from "next/link";
import type { Locale } from "@hxsl/tool-registry";
import { getLocalePath, getMessages, isLocale } from "../../../../lib/i18n";
import { localizedMetadata } from "../../../../lib/metadata";
import { getGuideExtras } from "../../../../lib/visible-extras";

type GuideCopy = { title: string; intro: string; sections: Array<[string, string]> };
const guides: Record<string, GuideCopy> = {
  "prepare-images-for-web": { title: "Prepare images for the web", intro: "A practical pass for choosing dimensions, format and quality before an image leaves your design workflow.", sections: [["Start with the output", "Choose the format from the destination. PNG is useful for crisp transparency, JPEG for photographs, WebP for broad modern delivery, and AVIF where the receiving browser and pipeline support it."], ["Resize before compressing", "A smaller decoded canvas is usually a bigger win than squeezing a file that is already far larger than its display size. The resize tool prevents accidental enlargement and checks decoded pixels."], ["Check the result", "HXSL shows the input and result sizes, dimensions and format after re-decoding the output. A conversion can legitimately be larger; the UI does not hide that change."]] },
  "pdf-privacy-basics": { title: "PDF privacy basics", intro: "What to check before sharing a PDF, and what a browser-local tool can and cannot promise.", sections: [["Know the difference", "Cropping changes the visible page box. Redaction must remove the underlying content. Flattening changes supported form and annotation behavior. These are different jobs and the tool pages label them separately."], ["Inspect before sharing", "Use metadata editing and the sanitize task to remove the declared categories you select. Verification reports structure, encryption and signature states separately; it does not turn unknown trust into trusted verification."], ["Keep the boundary visible", "Local tasks do not upload your file. Server tasks require a consent check and use short-lived results. Temporary deletion is lifecycle management, not a claim of physical SSD erasure."]] },
};

const localized: Partial<Record<Locale, Record<string, GuideCopy>>> = {
  ...Object.fromEntries(Object.entries(expandedTools).map(([locale, copy]) => [locale, copy.guides])),
  ko: additionalToolCopy.ko.guides as Record<string, GuideCopy>, it: additionalToolCopy.it.guides as Record<string, GuideCopy>,

  "zh-CN": {
    "prepare-images-for-web": { title: "为网页准备图片", intro: "在图片离开设计流程前，选择合适尺寸、格式和质量的实用步骤。", sections: [["先确定输出", "根据使用场景选择格式。PNG 适合清晰透明效果，JPEG 适合照片，WebP 适合现代网页传输，AVIF 则取决于接收浏览器和处理流程是否支持。"], ["先调整尺寸再压缩", "比起压缩已经远大于展示尺寸的文件，减小解码画布通常更有效。调整尺寸工具会避免意外放大，并检查解码像素。"], ["检查结果", "HXSL 会在重新解码后显示输入和结果的大小、尺寸与格式。转换后文件变大是可能的，界面不会隐藏这种变化。"]] },
    "pdf-privacy-basics": { title: "PDF 隐私基础", intro: "分享 PDF 前需要检查什么，以及浏览器本地工具能做和不能保证什么。", sections: [["区分不同操作", "裁切只改变可见页面区域。Redaction 必须移除底层内容。扁平化会改变受支持表单和批注的行为。这些是不同任务，工具页会分别说明。"], ["分享前检查", "使用元数据编辑和清理任务移除已声明的类别。验证会分别报告结构、加密和签名状态，不会把未知信任变成可信验证。"], ["保持边界清晰", "本地任务不会上传文件。服务端任务需要同意，并使用短期结果。临时删除是生命周期管理，不是物理 SSD 擦除承诺。"]] },
  },
  "zh-TW": {
    "prepare-images-for-web": { title: "為網頁準備圖片", intro: "在圖片離開設計流程前，選擇尺寸、格式與品質的實用步驟。", sections: [["先確定輸出", "依使用場景選擇格式。PNG 適合清晰透明效果，JPEG 適合照片，WebP 適合現代網頁傳輸，AVIF 則取決於接收瀏覽器與流程是否支援。"], ["先調整尺寸再壓縮", "比起壓縮遠大於顯示尺寸的檔案，減小解碼畫布通常更有效。調整尺寸工具會避免意外放大，並檢查解碼像素。"], ["檢查結果", "HXSL 會在重新解碼後顯示輸入與結果的大小、尺寸和格式。轉換後變大是可能的，介面不會隱藏這項變化。"]] },
    "pdf-privacy-basics": { title: "PDF 隱私基礎", intro: "分享 PDF 前應檢查的項目，以及瀏覽器本機工具能做與不能保證的事情。", sections: [["區分不同操作", "裁切只改變可見頁面區域。Redaction 必須移除底層內容。扁平化會改變支援的表單與註釋行為。這些是不同任務，工具頁會分別說明。"], ["分享前檢查", "使用中繼資料編輯與清理任務移除已宣告的類別。驗證會分別報告結構、加密與簽名狀態，不會把未知信任變成可信驗證。"], ["保持邊界清楚", "本機任務不會上傳檔案。伺服器任務需要同意並使用短期結果。暫存刪除是生命週期管理，不是實體 SSD 抹除承諾。"]] },
  },
  es: {
    "prepare-images-for-web": { title: "Preparar imágenes para la web", intro: "Pasos prácticos para elegir dimensiones, formato y calidad antes de sacar una imagen del flujo de diseño.", sections: [["Empieza por el destino", "Elige el formato según el uso. PNG sirve para transparencia nítida, JPEG para fotografías, WebP para entregas web modernas y AVIF cuando el navegador y el proceso lo admiten."], ["Redimensiona antes de comprimir", "Reducir el lienzo decodificado suele aportar más que comprimir un archivo mucho mayor que su tamaño de pantalla. La herramienta evita ampliar por accidente y comprueba los píxeles."], ["Comprueba el resultado", "HXSL muestra tamaños, dimensiones y formato después de volver a decodificar. Una conversión puede ser mayor y la interfaz lo muestra."]] },
    "pdf-privacy-basics": { title: "Privacidad básica de los PDF", intro: "Qué revisar antes de compartir un PDF y qué puede o no prometer una herramienta local del navegador.", sections: [["Conoce la diferencia", "Recortar cambia el cuadro visible. La redacción debe eliminar el contenido subyacente. Aplanar cambia el comportamiento de formularios y anotaciones compatibles. Son tareas distintas."], ["Inspecciona antes de compartir", "Usa la edición de metadatos y la limpieza para eliminar las categorías declaradas. La verificación separa estructura, cifrado y firma; no convierte confianza desconocida en confianza válida."], ["Mantén visible el límite", "Las tareas locales no suben el archivo. Las tareas de servidor piden consentimiento y usan resultados temporales. La eliminación temporal gestiona el ciclo de vida, no garantiza borrar físicamente un SSD."]] },
  },
  "pt-BR": {
    "prepare-images-for-web": { title: "Preparar imagens para a web", intro: "Um passo prático para escolher dimensões, formato e qualidade antes que a imagem saia do fluxo de design.", sections: [["Comece pelo destino", "Escolha o formato conforme o uso. PNG funciona para transparência nítida, JPEG para fotos, WebP para a web moderna e AVIF quando o navegador e o processo de destino oferecem suporte."], ["Redimensione antes de comprimir", "Um canvas decodificado menor costuma ajudar mais do que apertar um arquivo muito maior que sua exibição. A ferramenta evita aumento acidental e verifica os pixels."], ["Confira o resultado", "O HXSL mostra tamanhos, dimensões e formato após decodificar a saída novamente. Uma conversão pode ficar maior; a interface mostra essa mudança."]] },
    "pdf-privacy-basics": { title: "Noções de privacidade em PDF", intro: "O que conferir antes de compartilhar um PDF e o que uma ferramenta local do navegador pode ou não prometer.", sections: [["Entenda a diferença", "O recorte muda a área visível. A redação precisa remover o conteúdo subjacente. O achatamento altera formulários e anotações compatíveis. São tarefas diferentes."], ["Inspecione antes de compartilhar", "Use a edição de metadados e a limpeza para remover as categorias declaradas. A verificação separa estrutura, criptografia e assinatura; não transforma confiança desconhecida em confiança válida."], ["Mantenha o limite visível", "Tarefas locais não enviam o arquivo. Tarefas no servidor pedem consentimento e usam resultados temporários. A remoção temporária gerencia o ciclo de vida, não promete apagar fisicamente um SSD."]] },
  },
  de: {
    "prepare-images-for-web": { title: "Bilder für das Web vorbereiten", intro: "Praktische Schritte für Größe, Format und Qualität, bevor ein Bild den Design-Workflow verlässt.", sections: [["Mit dem Ziel beginnen", "Wähle das Format nach dem Ziel. PNG eignet sich für klare Transparenz, JPEG für Fotos, WebP für moderne Webauslieferung und AVIF, wenn Browser und Pipeline es unterstützen."], ["Vor dem Komprimieren skalieren", "Eine kleinere dekodierte Fläche bringt oft mehr als das Komprimieren einer Datei, die viel größer als ihre Anzeige ist. Das Werkzeug verhindert versehentliches Vergrößern und prüft Pixel."], ["Ergebnis prüfen", "HXSL zeigt Größe, Abmessungen und Format nach erneuter Dekodierung. Eine Konvertierung darf größer werden; die Oberfläche zeigt das."]] },
    "pdf-privacy-basics": { title: "PDF-Datenschutzgrundlagen", intro: "Was vor dem Teilen eines PDF zu prüfen ist und was ein lokales Browserwerkzeug leisten kann und nicht verspricht.", sections: [["Den Unterschied kennen", "Zuschneiden verändert den sichtbaren Seitenbereich. Redaction muss den zugrunde liegenden Inhalt entfernen. Flattening verändert unterstützte Formulare und Anmerkungen. Das sind verschiedene Aufgaben."], ["Vor dem Teilen prüfen", "Metadatenbearbeitung und Bereinigung entfernen die ausgewählten deklarierten Kategorien. Die Prüfung trennt Struktur, Verschlüsselung und Signatur; unbekanntes Vertrauen wird nicht zu vertrauenswürdigem Status."], ["Die Grenze sichtbar halten", "Lokale Aufgaben laden die Datei nicht hoch. Serveraufgaben fragen vorher und nutzen kurzlebige Ergebnisse. Temporäres Löschen verwaltet den Lebenszyklus, garantiert aber kein physisches Löschen einer SSD."]] },
  },
  fr: {
    "prepare-images-for-web": { title: "Préparer des images pour le web", intro: "Une méthode pratique pour choisir dimensions, format et qualité avant qu’une image ne quitte votre flux de création.", sections: [["Partir de la destination", "Choisissez le format selon l’usage. PNG convient à la transparence nette, JPEG aux photos, WebP au web moderne et AVIF lorsque le navigateur et la chaîne le prennent en charge."], ["Redimensionner avant de compresser", "Une surface décodée plus petite est souvent plus efficace que de compresser un fichier beaucoup trop grand pour son affichage. L’outil évite l’agrandissement involontaire et vérifie les pixels."], ["Vérifier le résultat", "HXSL affiche taille, dimensions et format après un nouveau décodage. Une conversion peut être plus grande et l’interface le montre."]] },
    "pdf-privacy-basics": { title: "Bases de la confidentialité des PDF", intro: "Ce qu’il faut vérifier avant de partager un PDF et ce qu’un outil local du navigateur peut ou ne peut pas promettre.", sections: [["Faire la différence", "Le recadrage change la zone visible. La rédaction doit supprimer le contenu sous-jacent. L’aplatissement modifie les formulaires et annotations pris en charge. Ce sont des tâches distinctes."], ["Inspecter avant de partager", "Utilisez la modification des métadonnées et le nettoyage pour supprimer les catégories déclarées. La vérification sépare structure, chiffrement et signature; elle ne transforme pas un statut inconnu en confiance établie."], ["Garder la limite visible", "Les tâches locales n’envoient pas votre fichier. Les tâches serveur demandent un consentement et utilisent des résultats temporaires. La suppression temporaire gère le cycle de vie, sans promettre l’effacement physique d’un SSD."]] },
  },
  ja: {
    "prepare-images-for-web": { title: "Web 用画像を準備する", intro: "画像をデザイン工程から出す前に、サイズ、形式、品質を選ぶための実用的な手順です。", sections: [["出力先から考える", "用途に合わせて形式を選びます。PNG は透明部分をきれいに保ち、JPEG は写真、WebP は現代の Web 配信、AVIF は受け側のブラウザーと処理環境が対応している場合に向いています。"], ["圧縮前にサイズを調整する", "表示サイズより大きすぎるファイルを圧縮するより、デコード後のキャンバスを小さくする方が効果的なことがあります。拡大を防ぎ、ピクセル数も確認します。"], ["結果を確認する", "HXSL は出力を再デコードしてサイズ、寸法、形式を表示します。変換後に大きくなる場合もあり、その変化を隠しません。"]] },
    "pdf-privacy-basics": { title: "PDF のプライバシー基礎", intro: "PDF を共有する前に確認することと、ブラウザー内のローカルツールができること・約束できないことを説明します。", sections: [["違いを理解する", "クロップは見えるページ領域を変えるだけです。Redaction は元の内容を削除する必要があります。Flatten は対応するフォームや注釈の動作を変えます。別々のタスクです。"], ["共有前に確認する", "メタデータ編集とサニタイズで、選択した明示的なカテゴリを削除します。検証は構造、暗号化、署名を分けて報告し、未知の信頼状態を信頼済みにはしません。"], ["境界を確認する", "ローカルタスクはファイルをアップロードしません。サーバータスクは同意を求め、短期結果を使います。一時削除はライフサイクル管理であり、SSD の物理消去を保証しません。"]] },
  },
};

function getGuide(locale: Locale, slug: string): GuideCopy | undefined { return localized[locale]?.[slug] ?? guides[slug]; }
export function generateStaticParams() { return Object.keys(guides).flatMap((slug) => LOCALES.map((locale) => ({ locale, slug }))); }
export async function generateMetadata({ params }: { params: Promise<{ locale: string; slug: string }> }): Promise<Metadata> { const { locale: rawLocale, slug } = await params; const guide = isLocale(rawLocale) ? getGuide(rawLocale, slug) : undefined; return guide && isLocale(rawLocale) ? localizedMetadata(rawLocale, `/guides/${slug}`, guide.title, guide.intro) : { title: "Not found" }; }
export default async function GuidePage({ params }: { params: Promise<{ locale: string; slug: string }> }) {
  const { locale: rawLocale, slug } = await params;
  if (!isLocale(rawLocale)) notFound();
  const locale = rawLocale as Locale;
  const guide = getGuide(locale, slug);
  if (!guide) notFound();
  const m = getMessages(locale);
  const toolHref = slug === "pdf-privacy-basics" ? "/pdf" : "/image";
  const extra = getGuideExtras(locale, slug);
  return <main className="shell content-page"><div className="eyebrow">{m.nav.guides}</div><h1>{guide.title}</h1><p>{guide.intro}</p>{guide.sections.map(([heading, body]) => <section key={heading}><h2>{heading}</h2><p>{body}</p></section>)}{extra.map(([heading, body]) => <section key={heading}><h2>{heading}</h2><p>{body}</p></section>)}<p><Link className="button button-secondary" href={getLocalePath(locale, toolHref)}>{m.nav.tools}</Link></p></main>;
}
import { expandedTools } from "../../../../lib/expanded-locales";
